### ISSUE TITLE
[Python] Get method not working on PersistentVolumeList

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1043]
### Problem description

When trying to retrieve an existing set of PersistentVolumes using `PersistentVolumeList.get` an error is thrown

### Errors & Logs

```
error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Users/lbriggs/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/lbriggs/.pyenv/versions/venv-3.8.2/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/lbriggs/.pyenv/versions/venv-3.8.2/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 34, in run_pulumi_func
        func()
      File "/Users/lbriggs/.pyenv/versions/venv-3.8.2/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 81, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/lbriggs/.pyenv/versions/venv-3.8.2/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 104, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Users/lbriggs/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 280, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/Users/lbriggs/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 39, in <module>
        pvl = PersistentVolumeList.get("volumes", "")
      File "/Users/lbriggs/.pyenv/versions/venv-3.8.2/lib/python3.8/site-packages/pulumi_kubernetes/core/v1/PersistentVolumeList.py", line 106, in get
        return PersistentVolumeList(resource_name, opts)
      File "/Users/lbriggs/.pyenv/versions/venv-3.8.2/lib/python3.8/site-packages/pulumi_kubernetes/core/v1/PersistentVolumeList.py", line 74, in __init__
        raise TypeError('Missing required property items')
    TypeError: Missing required property items
```

### Affected product version(s)

`v1.13.0`
`pulumi-kubernetes 1.5.8`

### Reproducing the issue

pvl = PersistentVolumeList.get("volumes", "")

### Suggestions for a fix

I suspect this is related to the fact the generated method expects a name, which doesn't make sense for a list, but not entirely sure

**Comment by lblackstone** [comment]
I'm not sure that the `.get` methods actually make sense for List resources, since those are an aggregation API rather than a single resource. This is probably an issue with our codegen library.
