### ISSUE TITLE
`TestHelm` failing in master

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#1057]
Last 5 master builds have failed with:

```
[ tes/tests/examples/python/helm ] Diagnostics:
[ tes/tests/examples/python/helm ]   pulumi:pulumi:Stack (helm-p-it-travis-job-helm-6c016160):
[ tes/tests/examples/python/helm ]     error: Program failed with an unhandled exception:
[ tes/tests/examples/python/helm ]     error: Traceback (most recent call last):
[ tes/tests/examples/python/helm ]       File "/home/travis/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
[ tes/tests/examples/python/helm ]         loop.run_until_complete(coro)
[ tes/tests/examples/python/helm ]       File "/opt/pyenv/versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
[ tes/tests/examples/python/helm ]         return future.result()
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
[ tes/tests/examples/python/helm ]         await run_pulumi_func(lambda: Stack(func))
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 34, in run_pulumi_func
[ tes/tests/examples/python/helm ]         func()
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in <lambda>
[ tes/tests/examples/python/helm ]         await run_pulumi_func(lambda: Stack(func))
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 104, in __init__
[ tes/tests/examples/python/helm ]         func()
[ tes/tests/examples/python/helm ]       File "/home/travis/.pulumi/bin/pulumi-language-python-exec", line 84, in <lambda>
[ tes/tests/examples/python/helm ]         coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
[ tes/tests/examples/python/helm ]       File "/opt/pyenv/versions/3.7/lib/python3.7/runpy.py", line 280, in run_path
[ tes/tests/examples/python/helm ]         run_name, mod_spec, pkg_name).copy()
[ tes/tests/examples/python/helm ]       File "/opt/pyenv/versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[ tes/tests/examples/python/helm ]         exec(code, run_globals)
[ tes/tests/examples/python/helm ]       File "./__main__.py", line 20, in <module>
[ tes/tests/examples/python/helm ]         rs = RandomString("random-string", length=8).result
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pulumi_random/random_string.py", line 128, in __init__
[ tes/tests/examples/python/helm ]         opts.version = utilities.get_version()
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pulumi_random/utilities.py", line 60, in get_version
[ tes/tests/examples/python/helm ]         pep440_version_string = pkg_resources.require(root_package)[0].version
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
[ tes/tests/examples/python/helm ]         needed = self.resolve(parse_requirements(requirements))
[ tes/tests/examples/python/helm ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
[ tes/tests/examples/python/helm ]         raise VersionConflict(dist, req).with_context(dependent_req)
[ tes/tests/examples/python/helm ]     pkg_resources.ContextualVersionConflict: (pulumi 1.14.0 (/home/travis/.local/share/virtualenvs/p-it-travis-job-helm-6c016160-567659396--8ksrWKE/lib/python3.7/site-packages), Requirement.parse('pulumi<3.0.0,>=2.0.0b2'), {'pulumi-random'})
[ tes/tests/examples/python/helm ]     error: an unhandled error occurred: Program exited with non-zero exit code: 1
[ tes/tests/examples/python/helm ]  
[ tes/tests/examples/python/helm ] 
```

**Comment by lblackstone** [comment]
This test seems to be pulling in changes from the `feature-2.0` branch somehow.
```
ERROR: pulumi-random 2.0.0b2 has requirement pulumi<3.0.0,>=2.0.0b2, but you'll have pulumi 1.14.0 which is incompatible.
```

`master` branch:
https://github.com/pulumi/pulumi-kubernetes/blob/39e2c0fc8d9ad3de5752bc2c0a2cdcadb0f50b7f/tests/examples/python/helm/requirements.txt#L1-L2

`feature-2.0` branch
https://github.com/pulumi/pulumi-kubernetes/blob/83777b4f1b02d1376848cd5c88d8752f11bb4ffe/tests/examples/python/helm/requirements.txt#L1-L2
