### ISSUE TITLE
Pulumi Python - Kubernetes Helm Chart, TypeError.

### ISSUE THREAD

**Issue by prkstaff** [pulumi/pulumi-kubernetes#1080]
### Problem description
I am trying to install a Istio helm chart using python as follow:

```
istio = Chart("istio151",
              chart="istio",
              namespace="istio-system",
              version="1.5.1"
)
```
Using these guides:
- [Pulumi docs](https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v2/chart/)
- [wordpress helm example](https://github.com/pulumi/examples/blob/master/kubernetes-ts-helm-wordpress/index.ts)

But I am getting a TypeError when running pulumi up.

### Errors & Logs

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/dev/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
        return future.result()
      File "/home/dev/projectspace/k8s-provision/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/dev/projectspace/k8s-provision/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 34, in run_pulumi_func
        func()
      File "/home/dev/projectspace/k8s-provision/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/dev/projectspace/k8s-provision/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 104, in __init__
        func()
      File "/home/dev/.pulumi/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 99, in <module>
        version="1.5.1"
    TypeError: __init__() got an unexpected keyword argument 'chart'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

#### Pulumi
v2.0.0
#### Pip freeze

> Arpeggio==1.9.2
> attrs==19.3.0
> certifi==2020.4.5.1
> chardet==3.0.4
> dill==0.3.1.1
> grpcio==1.28.1
> idna==2.8
> parver==0.3.0
> pkg-resources==0.0.0
> protobuf==3.11.3
> pulumi==2.0.0
> pulumi-gcp==3.1.0
> pulumi-kubernetes==2.0.0
> pulumi-random==2.0.0
> requests==2.21.0
> semver==2.9.1
> six==1.14.0
> urllib3==1.24.3

### Reproducing the issue
Project code here:
[source](https://gofile.io/?c=Aa3uzh)

**Comment by lblackstone** [comment]
Oh, it looks like there's a mistake in our 2.0 resource docs for the Chart resource in Python. Opened https://github.com/pulumi/docs/issues/3056 to track.

You actually need to use the `ChartOpts` class for several of those parameters. Here's an example: https://github.com/pulumi/pulumi-kubernetes/blob/71a939e892ce4523ad7ca29c0d121c7ad9b2497d/tests/examples/python/helm/__main__.py#L31-L32

Your chart would be something like
```py
from pulumi_kubernetes.helm.v2 import Chart, ChartOpts

istio = Chart("istio151", ChartOpts(
    chart="istio",
    namespace="istio-system",
    version="1.5.1"
))
```
