### ISSUE TITLE
Better error when helm command is not found

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-kubernetes#1081]
### Problem description

If I run a dotnet pulumi project that uses helm the error it gives when it cannot find helm is very generic. It took me a bit to understand that this runner container doesn't have helm instaledl which then I can quickly fix but at first I thought it couldn't find the local chart and not the helm binary itself. Can the error/exception give info when the helm binary is not found and directly state it?

### Errors & Logs

```
 error: Pulumi.ResourceException: No such file or directory
       at Pulumi.Kubernetes.Helm.ChartBase.<>c__DisplayClass0_0.<.ctor>b__1(ValueTuple`2 values)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

### Affected product version(s)

2.0.0

### Reproducing the issue

Create a resource using helm without the helm binary in your path. I have tried this using .net.

### Suggestions for a fix

Better error message stating that helm binary/command is not found.

**Comment by lblackstone** [comment]
This is for the helm.v2.Chart resource, which won't be updated. This should not be a problem for helm.v3.Chart or helm.v3.Release.
