### ISSUE TITLE
helm version fails

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-kubernetes#1169]
After updating from 1.6.0 to 2.3.1 ``pulumi up`` now fails with

```
    Error: Error: Command failed: helm version --short || true
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\helm\v2\helm.ts:238:23
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:249:35
        at Generator.next (<anonymous>)
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:17:12)
        at applyHelperAsync (C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:228:12)
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:182:65
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

if I execute ``helm version --short || true`` manually, I get the following output:

```
Client: v2.14.3+g0e7f3b6
Error: could not find tiller
'true' is not recognized as an internal or external command,
operable program or batch file.
```

(the ``|| true`` doesn't really make sense on windows)

https://github.com/pulumi/pulumi-kubernetes/blob/baa5a9f757c8874f5d62c3f5c0ed82931738b5ea/sdk/nodejs/helm/v2/helm.ts#L238

----------------

### Environment

OS: Windows 10 1809 x64
Pulumi version: v2.4.0
Pulumi-kubernetes: 2.3.1
Node: v12.16.1

**Comment by 0x53A** [comment]
The ``|| true`` __doesn't__ seem to be the issue, I went into **_C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\kubernetes\helm\v2\helm.js_** and changed it to ``let helmVerCmd = `helm version --short`;``, but it still failed:

```
    Error: Error: Command failed: helm version --short
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\helm\v2\helm.ts:238:23
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:249:35
        at Generator.next (<anonymous>)
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:17:12)
        at applyHelperAsync (C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:228:12)
        at C:\Progress\repos\customerdeployments\webapi-k8cluster\node_modules\@pulumi\pulumi\output.js:182:65
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by 0x53A** [comment]
I changed it to 

```
                var helmVer;
                try
                {
                    helmVer = child_process_1.execSync(helmVerCmd, {
                        stdio: ['pipe', 'pipe', 'ignore'],
                    }).toString();
                }
                catch (e) {
                    helmVer = e.stdout.toString();
                }
                console.log("###helmver", helmVer);
```

and now it works:

> ###helmver Client: v2.14.3+g0e7f3b6
