### ISSUE TITLE
Pulumi Python : pulumi_kubernetes.ConfigFile throws TypeError

### ISSUE THREAD

**Issue by kmr0877** [pulumi/pulumi-kubernetes#1226]
### Problem description
   I am trying to install KFServing using pulumi_kubernetes.ConfigFile using the code shown below.
Not sure if this is right approach to do it else if I am missing something?
Thanks for your help 😄 
```sh
kfserving = pulumi_kubernetes.ConfigFile(
    'kfserving', 'kfserving.yaml'
)
```

`kfserving.yaml` downloaded from [Kubeflow/KFserving](https://github.com/kubeflow/kfserving/tree/master/install/v0.3.0)

- Other: The above manifest file works fine with command `kubectl apply -f kfserving.yaml`

### Errors & Logs
```
error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "c:\users\appdata\local\programs\python\python37\Lib\asyncio\base_events.py", line 579, in run_until_complete
        return future.result()
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\stack.py", line 81, in run_in_stack       
        await run_pulumi_func(lambda: Stack(func))
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\stack.py", line 50, in run_pulumi_func    
        await RPC_MANAGER.rpcs.pop()
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\rpc_manager.py", line 67, in rpc_wrapper  
        result = await rpc
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\resource.py", line 474, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\rpc.py", line 68, in serialize_properties 
        result = await serialize_property(v, deps, input_transformer)
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\rpc.py", line 173, in serialize_property  
        value = await serialize_property(output.future(), deps, input_transformer)
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\runtime\rpc.py", line 159, in serialize_property  
        future_return = await asyncio.ensure_future(awaitable)
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\output.py", line 114, in get_value
        val = await self._future
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\output.py", line 155, in run
        value = await self._future
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\output.py", line 340, in gather_futures
        return await asyncio.gather(*value_futures)
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\output.py", line 114, in get_value
        val = await self._future
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\output.py", line 155, in run
        value = await self._future
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi\output.py", line 176, in run
        transformed: Input[U] = func(value)
      File "C:\Users\.virtualenvs\poc_kfserving-ag4xjMhI\lib\site-packages\pulumi_kubernetes\yaml.py", line 260, in <lambda>        
        CustomResourceDefinition(f"{x}", opts, **obj)))]
    TypeError: __init__() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Affected product version(s)
- Pulumi Version - v2.7.1
- Python 3.8.2

requirements.txt
```
pulumi>=2.0.0,<3.0.0
pulumi-kubernetes>=2.0.0,<3.0.0
```

**Comment by banerjip-paradyme** [comment]
try ./ before the file name if the file name is in the same folder as __main__.py. In my case, I have a sub-folder named 'yaml' and here is how I've gotten it to work:

`grafana_config=ConfigFile('grafana-config', './yaml/grafana-ingress.yaml')`

**Comment by lblackstone** [comment]
Just to make sure this isn't a problem with the arguments to ConfigFile, can you try

```py3
kfserving = pulumi_kubernetes.ConfigFile(
    "kfserving",
    file_id="kfserving.yaml",
)
```

Example usage is documented [here](https://www.pulumi.com/docs/reference/pkg/kubernetes/yaml/configfile/#local-file)

**Comment by lblackstone** [comment]
I'm going to close this issue since it appears to be a problem with the manifest, and the SDK is correctly flagging the input as a TypeError.

Alternatively, we could make the provider ignore the status field to better match the behavior of `kubectl`, but I think that might be surprising to users who thought they were setting the status.

cc @lukehoban

**Comment by kmr0877** [comment]
@lblackstone Seem like it is. Appreciate your response. Cheers
