### ISSUE TITLE
panic: interface conversion: interface {} is resource.PropertyMap, not string

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-kubernetes#1231]
```
pulumi:pulumi:Stack (argocd-dev):
    panic: interface conversion: interface {} is resource.PropertyMap, not string
    goroutine 68 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/resource.PropertyValue.StringValue(...)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.5.1-0.20200626210151-8961f5b0caae/go/common/resource/properties.go:362
    github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.parseKubeconfigPropertyValue(0x266aae0, 0xc0004075f0, 0x275d654, 0xa, 0xc0001bf708)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/provider/pkg/provider/util.go:85 +0x169
    github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.(*kubeProvider).DiffConfig(0xc0000e2f00, 0x2a63b40, 0xc000407560, 0xc0006aa0e0, 0xc0000e2f00, 0x251c101, 0xc0006a8480)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/provider/pkg/provider/provider.go:290 +0x5d5
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_DiffConfig_Handler.func1(0x2a63b40, 0xc000407560, 0x268f540, 0xc0006aa0e0, 0x26965c0, 0x3982808, 0x2a63b40, 0xc000407560)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.5.1-0.20200626210151-8961f5b0caae/proto/go/provider.pb.go:1773 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2a63b40, 0xc000406300, 0x268f540, 0xc0006aa0e0, 0xc0004a4680, 0xc0004a46a0, 0x0, 0x0, 0x2a16720, 0xc0003eaa10)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_DiffConfig_Handler(0x26e1e40, 0xc0000e2f00, 0x2a63b40, 0xc000406300, 0xc000288180, 0xc0003c2c00, 0x2a63b40, 0xc000406300, 0xc0006c2000, 0xf76)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.5.1-0.20200626210151-8961f5b0caae/proto/go/provider.pb.go:1775 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ec680, 0x2a7a5e0, 0xc000093800, 0xc0008b0300, 0xc0002cde60, 0x393d830, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc0001ec680, 0x2a7a5e0, 0xc000093800, 0xc0008b0300, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xcc9
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000462550, 0xc0001ec680, 0x2a7a5e0, 0xc000093800, 0xc0008b0300)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1
```

**Comment by jaxxstorm** [comment]
@stack72 and I have both seen this on many Kubernetes resources with the latest provider.

To repro:

- deploy a new helm chart (or other resource) and do `pulumi up` - everything will be fine. The one we both deployed was argocd. You can see my repro code [here](https://github.com/jaxxstorm/pulumi-examples/blob/master/typescript/aws/eks-platform/argocd/index.ts)
- make some modification, like a transformation. Rerun `pulumi up`. You get the above error

**Comment by lukehoban** [comment]
That stack trace I believe this means you passed an object instead of a string to the `kubeconfig` input on `new k8s.Provider`.  

Of course - it *definitely* should fail more cleanly, and arguably it should also accept an object as well as a string, but I expect you can workaround by calling `JSON.stringify` when you pass this in?

That explanation and stack trace don't appear related to the repro steps @jaxxstorm mentions above though - is it possible that those repro steps lead to a different error?  (or that they are not actually the exact repro steps that led here?)

**Comment by EvanBoyle** [comment]
I fixed the panic via https://github.com/pulumi/pulumi-kubernetes/pull/1373 by making the provider handle kubeconfig specified as either string or kubeconfig. 

The error happens during `DiffConfig` deserializing existing kubeconfig that was originally specified as an object. Our EKS library makes it very easy to get into this situation by specifying `kubeconfig` type as `any`. Is this intentional or can we tighten this up?

**Comment by EvanBoyle** [comment]
I opened this issue to track improving the EKS typing for `Cluster.kubeconfig` https://github.com/pulumi/pulumi-eks/issues/462
