### ISSUE TITLE
skipAwait annotation not respected for generic delete logic

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1232]
### Problem description

https://github.com/pulumi/pulumi-kubernetes/blob/d7871675b54727f63f1e2254d06653daf06cc8c8/provider/pkg/await/await.go#L463-L511

For resource types that don't have custom await logic, the provider currently ignores the `pulumi.com/skipAwait` annotation. If this annotation is set, the provider should immediately consider the resource to be deleted.

### Suggestions for a fix

Duplicate the logic here: https://github.com/pulumi/pulumi-kubernetes/blob/d7871675b54727f63f1e2254d06653daf06cc8c8/provider/pkg/await/await.go#L446-L447

**Comment by blampe** [comment]
Note that interrupting this can also result in a panic:
```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x107970948]
    goroutine 61 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.checkpointObject(0x14001a8f550, 0x0, 0x14000ea1dd0, {0x14000e7ac68, 0x2}, {0x14000e826e0, 0x1a})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2916 +0x38
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).Delete(0x140003f0000, {0x109108170, 0x14000ea1da0}, 0x14000e96840)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2591 +0x998
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Delete_Handler.func1({0x109108170?, 0x14000ea1da0?}, {0x108a64440?, 0x14000e96840?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/proto/go/provider_grpc.pb.go:705 +0xd0
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x109108170, 0x14000ea0de0}, {0x108a64440, 0x14000e96840}, 0x140006e9c40, 0x14000e39e48)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Delete_Handler({0x10901f760, 0x140003f0000}, {0x109108170, 0x14000ea0de0}, 0x14000e64f00, 0x140004881c0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/proto/go/provider_grpc.pb.go:707 +0x148
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400086e000, {0x109108170, 0x14001a08180}, {0x109159c00, 0x1400076a000}, 0x14001a1a000, 0x14000b1e360, 0x10c89dac0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xb58
    google.golang.org/grpc.(*Server).handleStream(0x1400086e000, {0x109159c00, 0x1400076a000}, 0x14001a1a000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xb20
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 70
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x13c

    error: update failed
```

**Comment by EronWright** [comment]
I wonder how replacement would combine with skipAwait on delete and with SSA.  Would the Apply call performed by the replacement be racing against finalization of the original?

**Comment by blampe** [comment]
After a lot of discussion we've decided to punt on this for the time being. The existing behavior is arguably buggy, so we need to be cautious about expanding the behavior to more resources.

To elaborate on why this is buggy, when we delete resources that respects skipAwait (Deployments, Jobs, StatefulSets, Namespaces, Pods, and ReplicationControllers) we don't wait for the deletion to succeed. In cases where a resource is getting delete-before-replaced, this combines with our SSA upsert behavior (https://github.com/pulumi/pulumi-kubernetes/issues/2998) to create a race condition where the resource could still be getting deleted when we upsert.

The annotation currently provides two functions when deleting relevant resources:
1. It makes deletion fast, but this is almost always better handled with a background or orphan delete (https://github.com/pulumi/pulumi-kubernetes/issues/2529).
2. It makes it possible to ignore stuck finalizers, which is generally not recommended but sometimes necessary.

We're currently considering changing the behavior to completely ignore the annotation during deletion. For users who need (1) there's another annotation available. It's unclear how many users actually rely on the annotation for (2) but we assume it's small -- if not, we might need a separate workaround for this case.
