### ISSUE TITLE
Constant 'looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached' errors

### ISSUE THREAD

**Issue by martaver** [pulumi/pulumi-kubernetes#1237]
### Problem description

I'm installing a few charts into my kubernetes cluster using pulumi... namely cert-manager, nginx-ingress and external-dns.

Since installing and configuring these three, my `pulumi up` fails about 70% of the time with the following error:
```
  pulumi:pulumi:Stack (environment-development):
    Error: looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached: Get "https://charts.jetstack.io/index.yaml": unexpected EOF
    Error: Error: Command failed: helm fetch cert-manager --untar --version 0.16.0 --destination /var/folders/n0/f14q1nqj3vbg5zyzygtrwt3h0000gn/T/tmp-5303750XZAygBZGge --repo https\://charts.jetstack.io/
    Error: looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached: Get "https://charts.jetstack.io/index.yaml": unexpected EOF
```

At the same time, basically every time I run `pulumi up`, each attempt takes between 5-8 minutes. Occasionally it works, and my changes are deployed, but usually I find myself having to try 4-5 times.

I only have around 70 resources in my stack total, I don't think that's so large that it would slow down pulumi significantly.

I have noticed (but I might just be chasing a red herring here...) that bandwidth seems to make the failures more consistent. E.g. if I'm streaming some video or something it _definitely_ will fail... otherwise if I have nothing else going on it seems to _often_ fail.

Also, it always fails on cert-manager. The helm resource is configured like this:
```
export const clusterCertManager = new k8s.helm.v3.Chart(
  'cluster-cert-manager',
  {
    namespace: clusterIngressNamespace.metadata.name,
      chart: 'cert-manager',
        fetchOpts: {
        repo: 'https://charts.jetstack.io/',
      },
    values: loadYaml(`${__dirname}/cluster-cert-manager.yaml`, draft => {
      draft.installCRDs = true;
    }),
    version: clusterCertManagerVersion,
  },
  {
    dependsOn: [clusterIngressNginx],
    provider: clusterProvider,
  }
);
```

I've also noticed that it seems to be downloading the chart every time I run `pulumi up`, even though nothing has changed. Shouldn't this be cached locally?

Anyway, I'd love some help figuring out what's going on over here. I love the approach pulumi is taking, but I keep running up against these weird issues like this thing, and other issues with request timeouts. It's gotten to the point where I'm seriously wondering whether something is wrong with the network adapter in my laptop - only my diagnostics don't find anything and it's only pulumi I ever have trouble with.

Any ideas?

### Errors & Logs

Full error:
```
```
  pulumi:pulumi:Stack (environment-development):
    Error: looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached: Get "https://charts.jetstack.io/index.yaml": unexpected EOF
    Error: Error: Command failed: helm fetch cert-manager --untar --version 0.16.0 --destination /var/folders/n0/f14q1nqj3vbg5zyzygtrwt3h0000gn/T/tmp-5303750XZAygBZGge --repo https\://charts.jetstack.io/
    Error: looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached: Get "https://charts.jetstack.io/index.yaml": unexpected EOF
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/helm/v3/helm.ts:252:23
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:228:12)
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:182:65
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    Error: Error: Command failed: helm fetch cert-manager --untar --version 0.16.0 --destination /var/folders/n0/f14q1nqj3vbg5zyzygtrwt3h0000gn/T/tmp-5303750XZAygBZGge --repo https\://charts.jetstack.io/
    Error: looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached: Get "https://charts.jetstack.io/index.yaml": unexpected EOF
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/helm/v3/helm.ts:252:23
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:228:12)
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:182:65
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
```

### Affected product version(s)

Pulumi: 2.8.2
@pulumi/kubernetes: 2.4.2

### Reproducing the issue

Not sure if this is possible to replicate... you could try installing cert-manager into a cluster and see how it performs compared to another chart maybe?

### Suggestions for a fix

I don't truly know what the problem is here, but I imagine that helm charts and their outputs at the time of deployment should be cached and re-used when checking for changes. Regardless, there shouldn't be any network requests if the repo, chart and version haven't changed.

**Comment by martaver** [comment]
Another weird fact I've noticed... while `pulumi up` is doing its thing, sometimes browser requests (e.g. loading a site in chrome) will hang until pulumi has finished 'failing'... after which, as soon as pulumi has finished and printed its error message, the browser requests will complete.

**Comment by martaver** [comment]
Another clue is that it will report `Duration: 1m21s` even though it took 5 minutes plus! Clearly something's getting properly hung up somewhere...

**Comment by lukehoban** [comment]
Very odd.

As noted in the original error message - this is just a failure trying to do `helm fetch cert-manager --untar --version 0.16.0 --destination /var/folders/n0/f14q1nqj3vbg5zyzygtrwt3h0000gn/T/tmp-5303750XZAygBZGge --repo https\://charts.jetstack.io/`.  So that part of things isn't really Pulumi-specific.

From other comments, it definitely sounds like there is a network bandwidth issue here.  And it may be that something else Pulumi is doing during the update is leading to the slowness.  Can you get any details on network usage by various `pulumi-*` processes during an update?  Also - if you can get a trace as in https://www.pulumi.com/docs/troubleshooting/#performance, that may be helpful for diagnosing.  Lastly, if you `pulumi stack export > stack.json`, can you share how big that resulting `stack.json` file is?

**Comment by lblackstone** [comment]
As Luke noted, I expect this is related to bandwidth. The Chart is not cached locally, so each update is fetching data remotely. See also: https://github.com/pulumi/pulumi-kubernetes/issues/1100

**Comment by martaver** [comment]
I should note that if I do the same `helm fetch` outside of pulumi, there's no problem.

One thing that is unique to `cert-manager` is that it also includes a bunch of CRDs that are really huge.

The `stack.json` file created is... 6.8mb...

If it was the massive stack state slowing things down, it might be possible that doing something with that state hangs a queue of async actions and that results in the cert-manager request failing...?

Trace of the same failure is here: https://drive.google.com/file/d/1kqEvY64UyEjRWx7gKcMhhitJww8sWe4m/view?usp=sharing

This one failed during plan. Sometimes it also fails during execution. I guess it downloads the chart all over again for execution?

The biggest culprit seems to be: /pulumirpc.ResourceProvider/Invoke (1m27.406s)

I'm not sure if there's any deeper info in the trace.

I'm on a pretty beefy internet connection here (100Mbs), and everything else seems to stream smoothly. I suspect it's something to do with the way `pulumi` is fetching this helm chart that causes the request to fail.

**Comment by martaver** [comment]
The CRDs for `cert-manager` ARE big... and downloading them constantly for a plan and again for execute isn't healthy, but that's also solvable with caching... I think the bigger issue here is why is the request failing and killing the plan and apply?

**Comment by lukehoban** [comment]
> The stack.json file created is... 6.8mb...

Okay - that's likely a core issue that drives the significant network congestion.  That said - ideally we would not let the `helm fetch` cause a failure here - and would be able to retry on failures that are determinably retryable to be more robust even when the network is dropping connections.

**Comment by lukehoban** [comment]
Given investigation so far - I think this issue should probably track specifically:
- [ ] Caching `helm fetch` downloads id/where possible
- [ ] Retrying `helm fetch` calls if/where possible

Other issues are tracking more general issues around performance with large state files.

**Comment by martaver** [comment]
It's weird the request fails - even if it's a huge 6mb+ chart of CRDs that should only take a few seconds. Less than 10s max.

Even if pulumi is busy with something else, the request at least should be able to complete without drama.

FYI, the CRDs that make the `cert-manager` are described in more detail here: https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests

**Comment by lukehoban** [comment]
> It's weird the request fails - even if it's a huge 6mb+ chart of CRDs that should only take a few seconds. Less than 10s max.

Agreed - there is no good reason this should be failing.  Even if heavily using the network, that should just lead to some incremental slowdown not to failures.   This could in part be due to the two action items I listed above - but may also be related to a flaky network somewhere between your machine and the various services being touched here that is leading to failures.  Either way - from the Pulumi side - we should address these two issues to try to improve reliability here as much as we can.

**Comment by martaver** [comment]
Hmmm I wish I knew how to diagnose a flakey network convincingly. Open to
suggestions if you have any!

**Comment by martaver** [comment]
In the absence of having better tools at my disposal, I tried a few different internet connections (work, hotspot etc) and get the same errors with each!

**Comment by martaver** [comment]
This is really quite painful. I'd really appreciate any work-around you could offer while you're working the problem.

Ideally, I wouldn't have to re-factor my stacks to isolate the charts in their own one...?

**Comment by lukehoban** [comment]
@lblackstone any thoughts on workarounds/mitigation’s ahead of the proposed improvements above?

**Comment by lblackstone** [comment]
Fetching the chart manually (with `helm fetch`) and then pointing to the local copy should help if the problem is network-related.

**Comment by martaver** [comment]
Hey guys, I'm back at our pulumi stack after two weeks, and saw the 2.9.0 release. Updated, and just reporting that this error seems to have gone.

There's still something evil going on with the way pulumi does network requests though. Whenever pulumi is working, I seem to have problems making requests from browsers... It's almost as if it takes over the whole network adapter.

**Comment by martaver** [comment]
More networking issues, slightly different context... getting this regularly now:
```
Error: looks like "https://charts.dgraph.io/" is not a valid chart repository or cannot be reached: Get "https://charts.dgraph.io/index.yaml": write tcp 192.168.1.19:50311->104.26.12.237:443: write: broken pipe
    Error: Error: Command failed: helm fetch dgraph --untar --version 0.0.9 --destination /var/folders/n0/f14q1nqj3vbg5zyzygtrwt3h0000gn/T/tmp-28651b4vZOjWD4Rny --repo https\://charts.dgraph.io/
    Error: looks like "https://charts.dgraph.io/" is not a valid chart repository or cannot be reached: Get "https://charts.dgraph.io/index.yaml": write tcp 192.168.1.19:50311->104.26.12.237:443: write: broken pipe
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/helm/v3/helm.ts:252:23
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:228:12)
        at /Users/martaver/Projects/sightful/git/sightful/node_modules/@pulumi/pulumi/output.js:182:65
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I suspect my router doesn't handle http2 properly or something. But at any rate - some feedback for you guys about the recoverability of the helm fetch requests. Don't get any of these errors running the commands from cli.

**Comment by martaver** [comment]
Oops, sorry seems like this error hasn't gone away after all:
```
error: Error: Command failed: helm fetch cert-manager --untar --version 0.16.0 --destination /var/folders/n0/f14q1nqj3vbg5zyzygtrwt3h0000gn/T/tmp-37232vcz764UwqFu5 --repo https\://charts.jetstack.io/
    Error: looks like "https://charts.jetstack.io/" is not a valid chart repository or cannot be reached: Get "https://charts.jetstack.io/index.yaml": unexpected EOF
```

Also, dunno what this means, but doesn't sound good (deploying a chart from a local filesystem path):
```
    coalesce.go:196: warning: cannot overwrite table with non table for tls (map[])
    coalesce.go:196: warning: cannot overwrite table with non table for tls (map[])
    coalesce.go:196: warning: cannot overwrite table with non table for tls (map[])
```

**Comment by martaver** [comment]
Okay, so some more info... I converted every helm chart we referenced into a local wrapper chart and referenced those using path in Chart resources. That stopped these errors. However some more clues:

1. It's definitely not just the jetstack chart, because I got the error with the other charts too as I converted them one by one. cert-manager's size seems to just be a coincidence.

2. The network congestion problems persist after all the charts have been converted (except they're not fatal now) - when pulumi is doing its thing, random websites, streams, connections etc still fail.

3. Network utilization is not large while pulumi is working, only like 15%... it's more like pulumi just occupies all the available sockets or something... if there is such a limit...

 4. The failure only ever happened on the helm fetch command. Since helm is an external program, I'm guess the helm tool also suffered from being 'locked out' of network traffic, much like the rest of my computer does.

I hope this helps you guys, pulumi is a great idea - using existing languages to declare state is a godsend. I really want this beast to be fast and stable :)

**Comment by lukehoban** [comment]
@martaver Apologies for the continued troubles - and thanks for continuing to share details.

We have never seen this kind of severe network degradation caused by Pulumi or Pulumi provider before - which does continue to make me think there must be something unique to either your environment or your program.  

At this point, I think the only way we'll be able to get more details is if you can share a repro of the problem (some part of your program which reproduces this issue reliably in one or more environments you have deployed it in that we can test in our own  environments to do more deep debugging). Is there anything you can share?

**Comment by martaver** [comment]
It's entirely possible that it's something to do with my Laptop's WiFi network adapter. I have no idea how to diagnose that though, because I don't really notice any problems doing anything else.

Also the problems persist if I switch Wifi networks.

I'm rolling 98 resources at the moment - just checking, that's not a particularly large set, is it?

The code I'm writing now is protected, unfortunately, but I can ask my employer if they are willing to share it. I'm not really sure how to approach isolating an issue like this.

It did occur to me that perhaps its http/2 that's causing the problems, because I remember I have noticed some strangeness in golang CLIs before and I believe they use http/2 as default.

I don't suppose there are any settings I could play with that would prefer http over http/2 or let me fiddle with parallelism?
