### ISSUE TITLE
Cert-Manager Helm Chart errors when trying to install CRD's 

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/pulumi-kubernetes#1318]
### Problem description

- I saw an issue in the following Pulumi Program: Kubernetes Provider

- Other: <DETAILS>

### Errors & Logs

When attempting to install the Cert-Manager Helm chart, with the "installCRDs" value set to true, Pulumi will fail with the following error:

```
    error: Running program 'C:\Temp\ptest\bin\Debug\netcoreapp3.1\ptest.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Failed to deserialize response message.")
       at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
       at Pulumi.Deployment.InvokeAsync[T](String token, InvokeArgs args, InvokeOptions options, Boolean convertResult)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()

```

Setting "installCRDs" to false does not generate this issue

### Affected product version(s)

2.6.0

### Reproducing the issue

Deploy the cert-manager helm chart with ""installCRDs" set to true

### Suggestions for a fix

There is a known issue with the 0.16 Cert-manager chart and older versions of Helm or Kubectl, where large nested CRD's cause an issue. The original Kubernetes issue is here - https://github.com/kubernetes/kubernetes/issues/91615.  This is fixed in Helm v3.3.1 so it may be that updating this in the provider will fix the issue.

That said, in Terraform this causes the provider to hang, rather than crash, so it may be a different issue, but is definitely related to CRD's.

**Comment by lblackstone** [comment]
I tested this with the following TS program, and it deployed successfully, so I'm going to marked this as fixed. Let me know if you're still seeing problems on `v2.6.1`+ of the k8s provider.

```ts
const certManagerNamespace = new k8s.core.v1.Namespace("certmanager", { metadata: { name: "cert-manager" } } );
const certmanager = new k8s.helm.v3.Chart("certmanager", {
    chart: "cert-manager",
    namespace: "cert-manager",
    version: "1.0.1",
    fetchOpts: {
        repo: "https://charts.jetstack.io"
    },
    values: {
        installCRDs: true,
    }
});
```
