### ISSUE TITLE
Using `appsv1.DeploymentStrategyPtr` helper results in panic when passing in nil

### ISSUE THREAD

**Issue by fedenusy** [pulumi/pulumi-kubernetes#1333]
### Problem description
* Using pulumi go
* I called the `appsv1.DeploymentStrategyPtr` helper while building a deployment object
* I passed in a `nil` value to the helper, which I expected would be handled gracefully
* Instead my program panicked and I got a stack trace that was hard to decipher

### Errors & Logs

```
Diagnostics:
  pulumi:pulumi:Stack (bos-staging):
    error: an unhandled error occurred: program exited with non-zero exit code: 2
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x17 pc=0x10997a6]
    goroutine 754 [running]:
    reflect.(*rtype).Kind(...)
    	GOROOT/src/reflect/type.go:777
    reflect.convertOp(0x6efb760, 0x0, 0x109616d)
    	GOROOT/src/reflect/value.go:2423 +0x26
    reflect.Value.Convert(0x0, 0x0, 0x0, 0x8282080, 0x6efb760, 0x199, 0x11, 0x12)
    	GOROOT/src/reflect/value.go:2413 +0x8a
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.awaitInputs(0x822f700, 0xc0000400b8, 0x6ed4580, 0xc0000e55e0, 0x94, 0x6efb760, 0xc0004996b0, 0x199, 0x8280000, 0x0, ...)
    	external/com_github_pulumi_pulumi_sdk_v2/go/pulumi/types.go:700 +0x83f
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.awaitInputs(0x822f700, 0xc0000400b8, 0x6fd7780, 0xc0000e5580, 0x99, 0x6faf420, 0xc0000f9f20, 0x199, 0xc000040000, 0x0, ...)
    	external/com_github_pulumi_pulumi_sdk_v2/go/pulumi/types.go:646 +0xdbf
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.toOutputWithContext.func1(0x6fd7780, 0xc0000e5580, 0x82465c0, 0xc0002e2700, 0x8282080, 0x6faf420, 0x822f700, 0xc0000400b8, 0x105b700)
    	external/com_github_pulumi_pulumi_sdk_v2/go/pulumi/types.go:738 +0x147
    created by github.com/pulumi/pulumi/sdk/v2/go/pulumi.toOutputWithContext
    	external/com_github_pulumi_pulumi_sdk_v2/go/pulumi/types.go:730 +0x1e8
```

### Affected product version(s)

pulumi v2.10.2, pulumi-kubernetes 2.6.1 (plugin + sdk)

### Reproducing the issue

```
package main

import (
	appsv1 "github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/apps/v1"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		args := &appsv1.DeploymentArgs{
			Metadata: metav1.ObjectMetaArgs{},
			Spec: &appsv1.DeploymentSpecArgs{
				Strategy: appsv1.DeploymentStrategyPtr(nil),
			},
		}
		_, err := appsv1.NewDeployment(ctx, "deploy", args)
		return err
	})
}
```

### Suggestions for a fix
I think the `appsv1.DeploymentStrategyPtr` helper should handle nils gracefully. Alternatively, the deployment should give a helpful error while getting registered.

**Comment by lblackstone** [comment]
This behavior is from pulumi's Go SDK rather than pulumi-kubernetes. A lot has changed there since this was opened, so I'm going to close this issue. Please open a new issue if this is still a problem.
