### ISSUE TITLE
Provider previews causing panics

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1365]
### Problem description

Certain previews can cause panics with the recent provider preview change enabled. k8s apimachinery libs involved in the DeepCopy operation are unable to handle computed values, which leads to the panic.

https://github.com/pulumi/pulumi-kubernetes/blob/743646b17c68a6863355f0109825f60de2ca0452/provider/pkg/provider/provider.go#L2277-L2278

### Errors & Logs

```
    panic: cannot deep copy resource.Computed
    goroutine 83 [running]:
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x59d0460, 0xc0009bb2f0, 0xc0018d72e0, 0xc0018b69f0)
    	/Users/levi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:466 +0x4e6
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x59649e0, 0xc0018b6570, 0xc0018b8076, 0xa)
    	/Users/levi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:450 +0x157
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x59649e0, 0xc0018b6540, 0x0, 0x0)
    	/Users/levi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:450 +0x157
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
    	/Users/levi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:435
    k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc001982020, 0xc0018e0120)
    	/Users/levi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/apis/meta/v1/unstructured/unstructured.go:146 +0x75
    github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.withLastAppliedConfig(0xc001982020, 0xc001982020, 0x5cfe9c8, 0xc0018b6540)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/provider/pkg/provider/provider.go:2278 +0x65
    github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.(*kubeProvider).Create(0xc000a2fa40, 0x5f25f60, 0xc0018b6360, 0xc0018ba0a0, 0xc000a2fa40, 0x597a001, 0xc0017e4f00)
    	/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/provider/pkg/provider/provider.go:1421 +0x3db
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler.func1(0x5f25f60, 0xc0018b6360, 0x5b0e1e0, 0xc0018ba0a0, 0x5b2dfe0, 0x6e60c70, 0x5f25f60, 0xc0018b6360)
    	/Users/levi/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.11.3-0.20201012185126-156aa9862e15/proto/go/provider.pb.go:2244 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x5f25f60, 0xc0018b6180, 0x5b0e1e0, 0xc0018ba0a0, 0xc0018c0100, 0xc0018c0120, 0x0, 0x0, 0x5ecbaa0, 0xc000289750)
    	/Users/levi/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f6
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler(0x5ba1e20, 0xc000a2fa40, 0x5f25f60, 0xc0018b6180, 0xc0018be060, 0xc0005b09a0, 0x5f25f60, 0xc0018b6180, 0xc0018c6380, 0x1ad)
    	/Users/levi/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.11.3-0.20201012185126-156aa9862e15/proto/go/provider.pb.go:2246 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022dba0, 0x5f40b00, 0xc00028ac00, 0xc000742300, 0xc0005aa120, 0x6dfe808, 0x0, 0x0, 0x0)
    	/Users/levi/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x522
    google.golang.org/grpc.(*Server).handleStream(0xc00022dba0, 0x5f40b00, 0xc00028ac00, 0xc000742300, 0x0)
    	/Users/levi/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcc5
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000572020, 0xc00022dba0, 0x5f40b00, 0xc00028ac00, 0xc000742300)
    	/Users/levi/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/Users/levi/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

### Affected product version(s)

Pulumi CLI versions >= `2.12.0`

### Reproducing the issue

Run the [MariaDB test](https://github.com/pulumi/pulumi-kubernetes/tree/master/tests/sdk/nodejs/examples/mariadb).

Running with `PULUMI_DISABLE_PROVIDER_PREVIEW=1 pulumi up` previews as expected, but `PULUMI_DISABLE_PROVIDER_PREVIEW=0 pulumi up` results in a panic.

**Comment by lblackstone** [comment]
@pgavlin I'm not very familiar with the preview changes, so unclear on the fix here. Could you take a look and let me know your thoughts?

**Comment by lblackstone** [comment]
After further investigation, this panic only occurs in conjunction with the changes from #1355. As long as we don't cut a new release, this shouldn't affect users yet.

**Comment by EronWright** [comment]
A follow-up: https://github.com/pulumi/pulumi-kubernetes/pull/2846
