### ISSUE TITLE
Pulumi failing to install kube-prometheus helm chart

### ISSUE THREAD

**Issue by bradkyle** [pulumi/pulumi-kubernetes#1389]
### Problem description
 
Truing to install kube-prometheus helm chart found the bitnami repository or the kube-prometheus stack from the prometheus community as follows:
 ```
 self.prometheus_chart = k8s.helm.v3.Chart(
            "prometheus",
             k8s.helm.v3.ChartOpts(
                chart="kube-prometheus-stack",
                fetch_opts=k8s.helm.v3.FetchOpts(
                    repo="https://prometheus-community.github.io/helm-charts",
                ),
        ))
```

```
 self.prometheus_chart = k8s.helm.v3.Chart(
            "prometheus-operator",
             k8s.helm.v3.ChartOpts(
                chart="kube-prometheus",
                fetch_opts=k8s.helm.v3.FetchOpts(
                    repo="https://charts.bitnami.com/bitnami",
                ),
        ))

```
returns the following error
  ```
pulumi:pulumi:Stack (dev):
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
    2020/11/24 03:27:45 info: skipping unknown hook: "crd-install"
 
   error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/thora/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/home/thora/.conda/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 451, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 75, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 197, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 183, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 154, in run
        value = await self._future
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 338, in gather_futures
        return await asyncio.gather(*value_futures)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 154, in run
        value = await self._future
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "/home/thora/.conda/lib/python3.7/site-packages/pulumi_kubernetes/yaml.py", line 519, in <lambda>
        CustomResourceDefinition(f"{x}", opts, **obj)))]
    TypeError: __init__() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

pip show pulumi

```
Name: pulumi
Version: 2.14.0
Summary: Pulumi's Python SDK
Home-page: https://github.com/pulumi/pulumi
Author: None
Author-email: None
License: Apache 2.0
Location: /home/thora/.conda/lib/python3.7/site-packages
Requires: dill, protobuf, grpcio
Required-by: pulumi-tls, pulumi-terraform, pulumi-random, pulumi-policy, pulumi-kubernetes, pulumi-kafka, pulumi-github, pulumi-gcp, pulumi-docker
```

pip show pulumi_kubernetes

```
Version: 2.7.2
Summary: A Pulumi package for creating and managing Kubernetes resources.
Home-page: https://pulumi.com
Author: None
Author-email: None
License: Apache-2.0
Location: /home/thora/.conda/lib/python3.7/site-packages
Requires: pulumi, semver, requests, parver, pyyaml
Required-by:

```
minikube version
```

minikube version: v1.13.0
commit: v1.13.0
```

Assuming this is an issue with the CustomResource def and not the helm chart? Any tips on how one should solve this? Thanks

**Comment by bradkyle** [comment]
Solved by #285

**Comment by bradkyle** [comment]
I haven't managed to solve this yet, it seems that there exists many incompatibilities with helm and pulumi though.  Some advice on this would be amazing

**Comment by aladmit** [comment]
I've installed kube-prometheus-stack a few weeks ago and it worked just fine. The only difference I see between our setups is SDK.

Maybe its SDK specific error? Have you tried to use TypeScript?

**Comment by bradkyle** [comment]
Thanks for the response, will give it a go with typescript.

**Comment by bradkyle** [comment]
Works perfectly with the typescript sdk, thanks

**Comment by gabomgp4** [comment]
@bradkyle , is it possible to know what version you tried?

It's not working for me. It failing with the error:

       error: resource prometheusrules.monitoring.coreos.com was not successfully created by the Kubernetes API server : customresourcedefinitions.apiextensions.k8s.io "prometheusrules.monitoring.coreos.com" already exists

And other similar errors.
