### ISSUE TITLE
Exception: invocation of pulumi:pulumi:getResource returned an error: unknown resource

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-kubernetes#1405]
With v2.15.5 of Pulumi / SDK, the yaml tests are failing, e.g.: https://github.com/pulumi/pulumi-kubernetes/pull/1402/checks?check_run_id=1538865963#step:25:3125

```
2020-12-11T18:02:30.3748677Z   pulumi:pulumi:Stack (helm-local-p-it-fv-az195-8-step1-50b55a5f):
2020-12-11T18:02:30.3750152Z     error: Program failed with an unhandled exception:
2020-12-11T18:02:30.3750973Z     error: Traceback (most recent call last):
2020-12-11T18:02:30.3752420Z       File "/home/runner/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
2020-12-11T18:02:30.3753431Z         loop.run_until_complete(coro)
2020-12-11T18:02:30.3754661Z       File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-12-11T18:02:30.3755641Z         return future.result()
2020-12-11T18:02:30.3757453Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
2020-12-11T18:02:30.3758879Z         await run_pulumi_func(lambda: Stack(func))
2020-12-11T18:02:30.3760711Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
2020-12-11T18:02:30.3762126Z         await RPC_MANAGER.rpcs.pop()
2020-12-11T18:02:30.3764093Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
2020-12-11T18:02:30.3765442Z         result = await rpc
2020-12-11T18:02:30.3767169Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/output.py", line 88, in is_value_known
2020-12-11T18:02:30.3768666Z         return await is_known and not contains_unknowns(await future)
2020-12-11T18:02:30.3770506Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/output.py", line 88, in is_value_known
2020-12-11T18:02:30.3771976Z         return await is_known and not contains_unknowns(await future)
2020-12-11T18:02:30.3773811Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/output.py", line 88, in is_value_known
2020-12-11T18:02:30.3775740Z         return await is_known and not contains_unknowns(await future)
2020-12-11T18:02:30.3776588Z       [Previous line repeated 4 more times]
2020-12-11T18:02:30.3778491Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 207, in do_get
2020-12-11T18:02:30.3780053Z         resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
2020-12-11T18:02:30.3781529Z       File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2020-12-11T18:02:30.3782564Z         result = self.fn(*self.args, **self.kwargs)
2020-12-11T18:02:30.3784719Z       File "/home/runner/.local/share/virtualenvs/p-it-fv-az195-8-step1-50b55a5f-077239366-Vs0JqhFI/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 205, in do_invoke
2020-12-11T18:02:30.3786154Z         raise Exception(details)
2020-12-11T18:02:30.3788668Z     Exception: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:p-it-fv-az195-8-step1-50b55a5f::helm-local::kubernetes:helm.sh/v2:Chart$kubernetes:core/v1:Pod::test-k5cb0rei/single-api-version-test
```

**Comment by lblackstone** [comment]
It's also occurring without me updating the `go.mod`, so I think the problem is in the latest SDK.
https://github.com/pulumi/pulumi-kubernetes/pull/1404/checks?check_run_id=1539107065

**Comment by lblackstone** [comment]
I was able to reproduce the error locally using the `v2.15.5` CLI. The test passes as expected with the `v2.15.4` CLI

**Comment by lblackstone** [comment]
Current theory is that this is related to https://github.com/pulumi/pulumi/pull/5897

**Comment by lblackstone** [comment]
Setting `PULUMI_DISABLE_RESOURCE_REFERENCES=1` works, which explains why this behavior started with CLI v2.15.5, when resource ref support became default.

**Comment by justinvp** [comment]
I know what’s going on, I’m just not sure what the right fix is...

Here’s a simpler repro:

```python
import pulumi
from pulumi_random import RandomString

class MyComponent(pulumi.ComponentResource):
    resource: pulumi.Output

    def __init__(self, name: str):
        super(MyComponent, self).__init__("test:index:MyComponent", name, dict())

        self.resource = self.urn.apply(lambda x: RandomString("rand", length=10))
        self.register_outputs({"resource": self.resource})

mycomponent = MyComponent("mycomponent")
```

An initial `pulumi up` succeeds.

After that successful deployment, running `pulumi up` again fails with:

```
$ pulumi up
Previewing update (dev)

View Live: redacted

     Type                 Name         Plan     Info
     pulumi:pulumi:Stack  pyrepro-dev           3 errors

Diagnostics:
  pulumi:pulumi:Stack (pyrepro-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 11 more times]
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 207, in do_get
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/justin/Desktop/2020/12/12/pyrepro/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 205, in do_invoke
        raise Exception(details)
    Exception: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::pyrepro::random:index/randomString:RandomString::rand
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

This is why we’re getting the error...

We’re calling `self.register_outputs({"resource": self.resource})` which registers the output, saving it in the state as a resource reference. From `pulumi stack export`:

```json
{
    "urn": "urn:pulumi:dev::pyrepro::test:index:MyComponent::mycomponent",
    "custom": false,
    "type": "test:index:MyComponent",
    "outputs": {
        "resource": {
            "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
            "id": "@7E8nmGwX{",
            "packageVersion": "",
            "urn": "urn:pulumi:dev::pyrepro::random:index/randomString:RandomString::rand"
        }
    },
    "parent": "urn:pulumi:dev::pyrepro::pulumi:pulumi:Stack::pyrepro-dev"
},
```

When `MyComponent` is instantiated, its outputs are deserialized as part of its `register_resource` call (to resolve its outputs). As part of deserializing its outputs, it sees that the resource output is a _resource reference_ and tries to get its state via invoking `pulumi:pulumi:getResource`. But this happens _before_ our call to instantiate `RandomString`, so it can’t find the` RandomString` in the map of resources for the plan.

I guess one potential fix would be to change the behavior of `pulumi:pulumi:getResource` to fallback to returning the state of an existing resource if it can’t be found among the map of new resources for the plan. Not sure if we want to do that, though.

**Comment by justinvp** [comment]
I can reproduce in .NET:

```c#
using System.Collections.Generic;
using System.Threading.Tasks;
using Pulumi;
using Pulumi.Random;

// Pulumi.Random doesn't have `ResourceType` attributes applied yet (registrations), so workaround by
// subclassing and applying the attribute to the subclass.
[ResourceType("random:index/randomString:RandomString", null)]
class MyRandomString : RandomString
{
    public MyRandomString(string name, RandomStringArgs args, CustomResourceOptions? options = null)
        : base(name, args, options)
    {
    }
}

class MyComponent : ComponentResource
{
    [Output("resource")]
    public Output<MyRandomString> Resource { get; private set; } = null!;

    public MyComponent(string name) : base("test:index:MyComponent", name)
    {
        Resource = Urn.Apply(_ => new MyRandomString("rand", new RandomStringArgs { Length = 10 }));
        RegisterOutputs(new Dictionary<string, object?>{ { "resource", Resource } });
    }
}

class MyStack : Stack
{
    public MyStack()
    {
        new MyComponent("mycomponent");
    }
}

class Program
{
    static Task<int> Main() => Deployment.RunAsync<MyStack>();
}
```

The initial update succeeds, and a subsequent update fails with the same error:

```
    error: Running program '/Users/justin/Desktop/2020/12/12/dotnetrepro/bin/Debug/netcoreapp3.1/dotnetrepro.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::dotnetrepro::random:index/randomString:RandomString::rand", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1607775024.091294000","description":"Error received from peer ipv4:127.0.0.1:53769","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::dotnetrepro::random:index/randomString:RandomString::rand","grpc_status":2}")
       at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
       at Pulumi.Deployment.InvokeRawAsync(String token, InvokeArgs args, InvokeOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.Logger.TryGetResourceUrnAsync(Resource resource)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

I believe the reason we don’t see the failure in .NET Kustomize is because `Directory`’s parent class, `CollectionComponentResource`, doesn’t annotate the property with `[Output("resources")]`, so we don’t attempt to actually deserialize the output (and thus, don't call `pulumi:pulumi:getResource` to lookup its state).

https://github.com/pulumi/pulumi-kubernetes/blob/3212c150c11ab27bb798cf7fad3bc3b6c7edfa53/sdk/dotnet/Yaml/Yaml.cs#L33-L35

**Comment by justinvp** [comment]
Here's a repro in Go:

```go
package main

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi-random/sdk/v2/go/random"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	ctx *pulumi.Context
}

func (m *module) Construct(name, typ string, args map[string]interface{}, urn string) (pulumi.Resource, error) {
	switch typ {
	case "random:index/randomString:RandomString":
		var resource random.RandomString
		err := m.ctx.RegisterResource("random:index/randomString:RandomString", name, nil, &resource, pulumi.URN_(urn))
		if err != nil {
			return nil, err
		}
		return &resource, nil
	default:
		return nil, errors.Errorf("unknown resource type %s", typ)
	}
}

type MyComponent struct {
	pulumi.ResourceState

	Resource pulumi.AnyOutput `pulumi:"resource"`
}

func (MyComponent) ElementType() reflect.Type {
	return reflect.TypeOf((*MyComponent)(nil)).Elem()
}

func NewMyComponent(ctx *pulumi.Context, name string, opts ...pulumi.ResourceOption) (*MyComponent, error) {
	myComponent := &MyComponent{}
	err := ctx.RegisterComponentResource("test:index:MyComponent", name, myComponent, opts...)
	if err != nil {
		return nil, err
	}

	res := myComponent.URN().Apply(func(interface{}) (interface{}, error) {
		return random.NewRandomString(ctx, "rand", &random.RandomStringArgs{
			Length: pulumi.Int(10),
		})
	})

	err = ctx.RegisterResourceOutputs(myComponent, pulumi.Map{
		"resource": res,
	})
	if err != nil {
		return nil, err
	}

	return myComponent, nil
}

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		module := &module{ctx: ctx}
		pulumi.RegisterResourceModule("random:index/randomString", "", module)

		_, err := NewMyComponent(ctx, "mycomponent")
		if err != nil {
			return err
		}
		return nil
	})
}
```

First `pulumi up` succeeds.

Second `pulumi up` fails:

```
    error: program failed: Invoke(pulumi:pulumi:getResource, ...): error: rpc error: code = Unknown desc = invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::gorepro::random:index/randomString:RandomString::rand
    exit status 1
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by justinvp** [comment]
Transferring this to `pulumi/pulumi` since it isn't specific to Kubernetes.
