### ISSUE TITLE
Excessive errors when Helm chart pull fails

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#1447]
I have some local client configuration problem, but the failure if I try to new up a `helm.Chart` is excessively verbose:

```
$ pulumi preview
Previewing update (dev)
     Type                            Name             Plan       Info
 +   pulumi:pulumi:Stack             gitlab-helm-dev  create     1 error; 56 messages
 +   └─ kubernetes:helm.sh/v3:Chart  gitlab           create

Diagnostics:
  pulumi:pulumi:Stack (gitlab-helm-dev):
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: chart "gitlab/gitlab" not found in https://charts.gitlab.io/ repository
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33
        at Http2CallStream.<anonymous> (/Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:333:22)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: chart "gitlab/gitlab" not found in https://charts.gitlab.io/ repository
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33
        at Http2CallStream.<anonymous> (/Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:333:22)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: chart "gitlab/gitlab" not found in https://charts.gitlab.io/ repository
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33
        at Http2CallStream.<anonymous> (/Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:333:22)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: chart "gitlab/gitlab" not found in https://charts.gitlab.io/ repository
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33
        at Http2CallStream.<anonymous> (/Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:333:22)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

    unhandled rejection: CONTEXT(75): Invoking function: tok=kubernetes:helm:template asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    unhandled rejection: CONTEXT(75): Invoking function: tok=kubernetes:helm:template asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    unhandled rejection: CONTEXT(75): Invoking function: tok=kubernetes:helm:template asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    unhandled rejection: CONTEXT(75): Invoking function: tok=kubernetes:helm:template asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

    error: Running program '/Users/joeduffy/temp/gitlab-helm' failed with an unhandled exception:
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: chart "gitlab/gitlab" not found in https://charts.gitlab.io/ repository
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33
        at Http2CallStream.<anonymous> (/Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:333:22)
        at /Users/joeduffy/temp/gitlab-helm/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Feels like at a minimum, we should get rid of the rejected promise errors here and clean up the error message.

**Comment by eugenekurasov** [comment]
Hi, try chart name `gitlab` instead `gitlab/gitlab`.

I found equal command in helm. It is:
`helm install some-your-name gitlab/gitlab --repo https://charts.gitlab.io/ `

**Comment by EronWright** [comment]
Seems the problem doesn't repro anymore:

```
❯ p preview
Previewing update (dev)


     Type                            Name            Plan       Info
 +   pulumi:pulumi:Stack             issue-1447-dev  create     1 error; 2 warnings; 2 messages
 +   └─ kubernetes:helm.sh/v3:Chart  gitlab          create     

Diagnostics:
  pulumi:pulumi:Stack (issue-1447-dev):
    error: Running program '/Users/eronwright/Pulumi/pulumi-hacking/kubernetes/issue-1447/index.ts' failed with an unhandled exception:
    <ref *1> Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: chart "gitlab/gitlab" not found in https://charts.gitlab.io/ repository
        at Object.callback (/Users/eronwright/Pulumi/pulumi-hacking/kubernetes/issue-1447/node_modules/@pulumi/runtime/invoke.ts:172:37)
        at Object.onReceiveStatus (/Users/eronwright/Pulumi/pulumi-hacking/kubernetes/issue-1447/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/Users/eronwright/Pulumi/pulumi-hacking/kubernetes/issue-1447/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/Users/eronwright/Pulumi/pulumi-hacking/kubernetes/issue-1447/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /Users/eronwright/Pulumi/pulumi-hacking/kubernetes/issue-1447/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      promise: Promise { <rejected> [Circular *1] }
    }

    (node:96825) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)

```

Closing as completed.
