### ISSUE TITLE
Improve error messages from failing getResourceProperty calls in TypeScript

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-kubernetes#1494]
When repairing one of the bit-rotted examples I ran into the following stack trace:

```
   error: Running program '/Users/anton/examples/classic-azure-ts-aks-helm' failed with an unhandled exception:
    TypeError: Cannot read property 'status' of undefined
        at ../@pulumi/yaml/yaml.ts:2373:33
        at ../@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at ../@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (../@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (../@pulumi/pulumi/output.js:228:12)
        at ../@pulumi/pulumi/output.js:182:65
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This happens when user code in the example (index.ts) makes incorrect assumptions about returned properties, e.g.:

```
export let serviceIP = apache
    .getResourceProperty("v1/Service", "apache", "status")
```

It would be very helpful, if possible:

* localize the error to the getResourceProperty call; initially I was confused and thought that some kubernetes related functionality is failing 

* help the user navigate which property names are indeed available, to make it simple to fix the code  

## To reproduce

* Follow https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm

* Deliberately break getResourceProperty call, say s/apache/apacheBroken/

* `pulumi up`

## Affected feature

TypeScript SDK

**Comment by jkodroff** [comment]
We should still fix this.
