### ISSUE TITLE
Uncatched exception with helm.v3.Release

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-kubernetes#1728]
We got an error in CI with helm.v3.Release, rerun worked fine:
```
Diagnostics:
  kubernetes:helm.sh/v3:Release (dapr):
    error: transport is closing
 
  pulumi:pulumi:Stack (customer-portal-uat):
    2021/09/21 16:59:54 [DEBUG] Chart dependencies are up to date.
    2021/09/21 16:59:56 [DEBUG] Chart dependencies are up to date.
    panic: fatal: An assertion has failed
    goroutine 1062 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.9.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.9.0/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*patchConverter).addPatchValueToDiff(0xc003632f78, 0xc003714f20, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2798 +0xb6b
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*patchConverter).addPatchMapToDiff(0xc003632f78, 0xc003749b10, 0x1, 0x1, 0xc00372b590, 0xc00372b890, 0xc00372b980, 0xc00372ba40, 0xc003749b00, 0x10, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2898 +0x31d
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*patchConverter).addPatchValueToDiff(0xc003632f78, 0xc003749b10, 0x1, 0x1, 0x213cc00, 0xc00372b590, 0x213cc00, 0xc00372b890, 0x213cc00, 0xc00372b980, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2819 +0x17a
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*patchConverter).addPatchMapToDiff(0xc003632f78, 0x0, 0x0, 0x0, 0xc00372b560, 0xc00372b830, 0xc00372b920, 0xc00372b9e0, 0x0, 0xc003632f98, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2898 +0x31d
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.convertPatchToDiff(0xc00372b560, 0xc00372b830, 0xc00372b920, 0xc00372b9e0, 0xc003714e40, 0x2, 0x2, 0x2, 0x90, 0x0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2725 +0x119
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*helmReleaseProvider).Diff(0xc00017f9f0, 0x27d4b48, 0xc003dd3da0, 0xc003dc9420, 0x195, 0xc002b2c202, 0xc0002426e0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:623 +0xc6a
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*kubeProvider).Diff(0xc000374f00, 0x27d4b48, 0xc003dd3da0, 0xc003dc9420, 0xc000374f00, 0x215a401, 0xc003dff900)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1363 +0x19a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1(0x27d4b48, 0xc003dd3da0, 0x2341840, 0xc003dc9420, 0x23588c0, 0x3970530, 0x27d4b48, 0xc003dd3da0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.9.0/proto/go/provider.pb.go:2576 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x27d4b48, 0xc003dd3830, 0x2341840, 0xc003dc9420, 0xc003da3180, 0xc003db9698, 0x0, 0x0, 0x278b9e0, 0xc0002e2070)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler(0x23f8540, 0xc000374f00, 0x27d4b48, 0xc003dd3830, 0xc003ddf1a0, 0xc00066e020, 0x27d4b48, 0xc003dd3830, 0xc003df6000, 0x17c5)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.9.0/proto/go/provider.pb.go:2578 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000379180, 0x27f1458, 0xc000375c80, 0xc003de0fc0, 0xc000746000, 0x390d008, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00026d140, 0xc000379180, 0x27f1458, 0xc000375c80, 0xc003de0fc0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
```

**Comment by mikhailshilkov** [comment]
Hi @jancespivo thank you for reporting this.

It's a bit hard to tell what's going on purely based on this error message. Do you have a code snippet that we could run to reproduce?

**Comment by jancespivo** [comment]
Hi @mikhailshilkov It is hard to reproduce IMO. We experienced this error only once and it was in CI pipeline. There were some connection issues though :shrug: I've tried to disconnect during the `pulumi up` multiple times, but without "success" :(

**Comment by mikhailshilkov** [comment]
@viveklak FYI in case you ever see this.

**Comment by ruckc** [comment]
I keep running into this when I am creating a new k8s resource and forget to specify the resource `provider` argument manually in the `CustomResourceOptions` argument.

**Comment by EronWright** [comment]
I think this is fixed by: https://github.com/pulumi/pulumi-kubernetes/pull/1850

Note how the assertion failure (`panic: fatal: An assertion has failed`) lacks a detailed message, implying that the provider version is from before #1850 (which improves the assertion check to include a message), ie. before `v3.14.0`.

Please re-open if you see this error again.
