### ISSUE TITLE
Helm invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lkt82** [pulumi/pulumi-kubernetes#1844]
## Hello!
When updating a helm chart with a new chart value I am getting this error.

## Issue details

`   panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x0 pc=0x2773d47]
    goroutine 119 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/await.makeServiceInitAwaiter(0xc000afe030, 0x3141ae0, 0xc000afc2c0, 0xc001252820, 0xc9, 0xc00228a14c, 0x2, 0xc00228ff00, 0xc0009c9590, 0xc001438cd0, ...)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/service.go:84 +0x67
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/await.awaitServiceUpdate(0xc000afe030, 0x3141ae0, 0xc000afc2c0, 0xc001252820, 0xc9, 0xc00228a14c, 0x2, 0xc00228ff00, 0xc0009c9590, 0xc001438cd0, ...)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/service.go:112 +0x45
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/await.Update(0x3141ae0, 0xc000afc2c0, 0xc000afe030, 0xc001252820, 0xc9, 0xc00228a14c, 0x2, 0x0, 0x0, 0xc0009c9590, ...)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/await.go:430 +0xb35
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*kubeProvider).Update(0xc000584900, 0x3141b88, 0xc00228c5d0, 0xc002046c00, 0xc000584900, 0x2a6da01, 0xc00228f380)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2166 +0xfc5
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1(0x3141b88, 0xc00228c5d0, 0x2c8e4a0, 0xc002046c00, 0x2c7a900, 0x438ca60, 0x3141b88, 0xc00228c5d0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2638 +0x90
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3141b88, 0xc00207ac60, 0x2c8e4a0, 0xc002046c00, 0xc002074a00, 0xc00204ddb8, 0x0, 0x0, 0x30f7600, 0xc000326e60)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x31c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler(0x2d1d9a0, 0xc000584900, 0x3141b88, 0xc00207ac60, 0xc0020fa060, 0xc000abd100, 0x3141b88, 0xc00207ac60, 0xc0009f4c80, 0x1905)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2640 +0x15e
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000894000, 0x315f238, 0xc000584d80, 0xc0020f8000, 0xc000aa1f50, 0x4312870, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc000894000, 0x315f238, 0xc000584d80, 0xc0020f8000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000ad4830, 0xc000894000, 0x315f238, 0xc000584d80, 0xc0020f8000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xb2
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd`

### Steps to reproduce

1. Use the ingress-nginx chart
2. Provide a value for controller.service.annotations   "service.beta.kubernetes.io/service.beta.kubernetes.io/azure-pip-tags"

Expected: The service annotations to be updated.
Actual: Go panic

**Comment by mikhailshilkov** [comment]
@lkt82 Sorry for the trouble! Could you please add a code snippet to reproduce this? (including before and after the update)

**Comment by lkt82** [comment]
Okay I tried creating this snipped based on the real code.

before

```
            const string namespaceName = "ingress-system";

            var @namespace = new Namespace("ns",
                new NamespaceArgs
                {
                    Metadata = new ObjectMetaArgs
                    {
                        Name = namespaceName
                    }
                });

            const string name = "ingress-nginx";

            var tags = new InputMap<string>
            {
                { AzureTags.Environment, "test" },
                { AzureTags.ManagedBy, "Pulumi" },
            };

            var values = tags.Apply(liftedTags =>
            {
                return new Dictionary<string, object>
                    {
                        {
                            "controller", new Dictionary<string, object>
                            {
                                {
                                    "service", new Dictionary<string, object>
                                    {
                                        { "externalTrafficPolicy", "Local" },
                                        {
                                            "annotations", new Dictionary<string, object>
                                            {
                                                { "service.beta.kubernetes.io/azure-dns-label-name", "snippet43543.westeurope.cloudapp.azure.com"}
                                            }
                                        }
                                    }
                                },
                                {
                                    "metrics", new Dictionary<string, object>
                                    {
                                        { "enabled", false }
                                    }
                                },
                                {
                                    "podAnnotations", new Dictionary<string, object>
                                    {
                                        { "prometheus.io/port", 10254 },
                                        { "prometheus.io/scrape", false }
                                    }
                                },
                                {
                                    "autoscaling", new Dictionary<string, object>
                                    {
                                        { "enabled", false }
                                    }
                                },
                                { "replicaCount", 1 },
                                {
                                    "image", new Dictionary<string, object>
                                    {
                                        { "allowPrivilegeEscalation", false }
                                    }
                                },
                                {
                                    "containerPort", new Dictionary<string, object>
                                    {
                                        { "http", 8080 },
                                        { "https", 8081 }
                                    }
                                },
                                {
                                    "extraArgs", new Dictionary<string, object>
                                    {
                                        { "http-port", 8080 },
                                        { "https-port", 8081 },
                                        { "logtostderr", string.Empty },
                                        { "stderrthreshold", 3 }
                                    }
                                }
                            }
                        },
                        { "fullnameOverride", name }
                    };
            });

            var chart = new Chart(name,
                new ChartArgs
                {
                    Namespace = @namespace.Metadata.Apply(c => c.Name),
                    ResourcePrefix = "snippet",
                    Chart = name,
                    Version = "4.0.6",
                    IncludeTestHookResources = false,
                    FetchOptions = new ChartFetchArgs
                    {
                        Repo = "https://kubernetes.github.io/ingress-nginx"
                    },
                    Values = values
                });
```
After


```
            const string namespaceName = "ingress-system";

            var @namespace = new Namespace("ns",
                new NamespaceArgs
                {
                    Metadata = new ObjectMetaArgs
                    {
                        Name = namespaceName
                    }
                });

            const string name = "ingress-nginx";

            var tags = new InputMap<string>
            {
                { AzureTags.Environment, "test" },
                { AzureTags.ManagedBy, "Pulumi" },
            };

            var values = tags.Apply(liftedTags =>
            {
                return new Dictionary<string, object>
                    {
                        {
                            "controller", new Dictionary<string, object>
                            {
                                {
                                    "service", new Dictionary<string, object>
                                    {
                                        { "externalTrafficPolicy", "Local" },
                                        {
                                            "annotations", new Dictionary<string, object>
                                            {
                                                { "service.beta.kubernetes.io/azure-dns-label-name", "snippet43543.westeurope.cloudapp.azure.com"},
                                                { "service.beta.kubernetes.io/service.beta.kubernetes.io/azure-pip-tags",string.Join(',',liftedTags.Select(c=> $"{c.Key}={c.Value}")) }
                                            }
                                        }
                                    }
                                },
                                {
                                    "metrics", new Dictionary<string, object>
                                    {
                                        { "enabled", false }
                                    }
                                },
                                {
                                    "podAnnotations", new Dictionary<string, object>
                                    {
                                        { "prometheus.io/port", 10254 },
                                        { "prometheus.io/scrape", false }
                                    }
                                },
                                {
                                    "autoscaling", new Dictionary<string, object>
                                    {
                                        { "enabled", false }
                                    }
                                },
                                { "replicaCount", 1 },
                                {
                                    "image", new Dictionary<string, object>
                                    {
                                        { "allowPrivilegeEscalation", false }
                                    }
                                },
                                {
                                    "containerPort", new Dictionary<string, object>
                                    {
                                        { "http", 8080 },
                                        { "https", 8081 }
                                    }
                                },
                                {
                                    "extraArgs", new Dictionary<string, object>
                                    {
                                        { "http-port", 8080 },
                                        { "https-port", 8081 },
                                        { "logtostderr", string.Empty },
                                        { "stderrthreshold", 3 }
                                    }
                                }
                            }
                        },
                        { "fullnameOverride", name }
                    };
            });

            var chart = new Chart(name,
                new ChartArgs
                {
                    Namespace = @namespace.Metadata.Apply(c => c.Name),
                    ResourcePrefix = "snippet",
                    Chart = name,
                    Version = "4.0.6",
                    IncludeTestHookResources = false,
                    FetchOptions = new ChartFetchArgs
                    {
                        Repo = "https://kubernetes.github.io/ingress-nginx"
                    },
                    Values = values
                });
```

**Comment by lkt82** [comment]
The annotations  `service.beta.kubernetes.io/service.beta.kubernetes.io/azure-pip-tags`  creates the panic

**Comment by viveklak** [comment]
> The annotations `service.beta.kubernetes.io/service.beta.kubernetes.io/azure-pip-tags` creates the panic

The issue seems to be malformed annotation name here. You probably want this instead: `service.beta.kubernetes.io/azure-pip-tags`. Essentially the patch call in the following line of code: https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/await/await.go#L397
 is failing with a `422` response code due to the invalid format for the annotation but for whatever reason the client-go package is not returning an error here which would make the above error apparent. Will investigate if this is a known issue with the k8s client/reproducible with a newer version.

**Comment by EronWright** [comment]
I was unable to reproduce the panic issue, assumedly the root cause was already fixed. As expected, the malformed annotation caused the deployment to fail, and the error message is clear.

If the annotation is applied during an update, the results are:
```
     Type                                                              Name                                                   Status 
     pulumi:pulumi:Stack                                               issue-1844-dev                                         **faile
     └─ kubernetes:helm.sh/v3:Chart                                    snippet-ingress-nginx                                         
 ~      ├─ kubernetes:core/v1:Service                                  snippet-ingress-system/ingress-nginx-controller        **updat
        ├─ kubernetes:core/v1:ServiceAccount                           snippet-ingress-system/ingress-nginx-admission                
        ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole         snippet-ingress-nginx-admission                               
        ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding  snippet-ingress-nginx-admission                               
        ├─ kubernetes:rbac.authorization.k8s.io/v1:Role                snippet-ingress-system/ingress-nginx-admission                
        ├─ kubernetes:rbac.authorization.k8s.io/v1:RoleBinding         snippet-ingress-system/ingress-nginx-admission                
        ├─ kubernetes:batch/v1:Job                                     snippet-ingress-system/ingress-nginx-admission-create         
        └─ kubernetes:batch/v1:Job                                     snippet-ingress-system/ingress-nginx-admission-patch          

Diagnostics:
  kubernetes:core/v1:Service (snippet-ingress-system/ingress-nginx-controller):
    error: 1 error occurred:
        * the Kubernetes API server reported that "ingress-system/ingress-nginx-controller" failed to fully initialize or become live: Service "ingress-nginx-controller" is invalid: metadata.annotations: Invalid value: "service.beta.kubernetes.io/service.beta.kubernetes.io/azure-pip-tags": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
        * 
  pulumi:pulumi:Stack (issue-1844-dev):
    error: update failed

Resources:
    20 unchanged

Duration: 2s
```

If the annotation is applied during the initial deployment, the results are:

```
     Type                                                                             Name                                                       Status                          Info
 +   pulumi:pulumi:Stack                                                              issue-1844-dev                                             **creating failed (0.00s)**     1 error
 +   ├─ kubernetes:helm.sh/v3:Chart                                                   snippet-ingress-nginx                                      created                         
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:Role                               snippet-ingress-system/ingress-nginx                       created (4s)                    
 +   │  ├─ kubernetes:core/v1:Service                                                 snippet-ingress-system/ingress-nginx-controller            **creating failed**             1 error
 +   │  ├─ kubernetes:networking.k8s.io/v1:IngressClass                               snippet-nginx                                              created (4s)                    
 +   │  ├─ kubernetes:core/v1:ServiceAccount                                          snippet-ingress-system/ingress-nginx-admission             created (4s)                    1 warning
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        snippet-ingress-system/ingress-nginx-admission             created (4s)                    1 warning
 +   │  ├─ kubernetes:core/v1:ConfigMap                                               snippet-ingress-system/ingress-nginx-controller            created (0.00s)                 
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 snippet-ingress-nginx                                      created (4s)                    
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 snippet-ingress-nginx-admission                            created (4s)                    1 warning
 +   │  ├─ kubernetes:batch/v1:Job                                                    snippet-ingress-system/ingress-nginx-admission-create      created (12s)                   1 warning
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        snippet-ingress-nginx                                      created (4s)                    
 +   │  ├─ kubernetes:core/v1:Service                                                 snippet-ingress-system/ingress-nginx-controller-admission  created (32s)                   
 +   │  ├─ kubernetes:apps/v1:Deployment                                              snippet-ingress-system/ingress-nginx-controller            **creating failed**             1 error
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        snippet-ingress-nginx-admission                            created (4s)                    1 warning
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:Role                               snippet-ingress-system/ingress-nginx-admission             created (4s)                    1 warning
 +   │  ├─ kubernetes:batch/v1:Job                                                    snippet-ingress-system/ingress-nginx-admission-patch       created (12s)                   1 warning
 +   │  ├─ kubernetes:core/v1:ServiceAccount                                          snippet-ingress-system/ingress-nginx                       created (0.00s)                 
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        snippet-ingress-system/ingress-nginx                       created (4s)                    
 +   │  └─ kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration  snippet-ingress-nginx-admission                            created (4s)                    
 +   └─ kubernetes:core/v1:Namespace                                                  ns                                                         created (0.00s)                 
 
Diagnostics:
  pulumi:pulumi:Stack (issue-1844-dev):
    error: update failed
 
  kubernetes:core/v1:Service (snippet-ingress-system/ingress-nginx-controller):
    error: resource ingress-system/ingress-nginx-controller was not successfully created by the Kubernetes API server : Service "ingress-nginx-controller" is invalid: metadata.annotations: Invalid value: "service.beta.kubernetes.io/service.beta.kubernetes.io/azure-pip-tags": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')

  kubernetes:apps/v1:Deployment (snippet-ingress-system/ingress-nginx-controller):
    error: 4 errors occurred:
    	* resource ingress-system/ingress-nginx-controller was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'ingress-nginx-controller' timed out waiting to be Ready
    	* [MinimumReplicasUnavailable] Deployment does not have minimum availability.
    	* Minimum number of live Pods was not attained
    	* [Pod ingress-system/ingress-nginx-controller-d4dfc46d9-vljrz]: containers with unready status: [controller] -- [CrashLoopBackOff] back-off 5m0s restarting failed container=controller pod=ingress-nginx-controller-d4dfc46d9-vljrz_ingress-system(35062b85-0b01-4ee0-b3b2-5dc278c97b61)
 
Resources:
    + 19 created
```
