### ISSUE TITLE
`.status.loadBalancer` field was not updated with a hostname/IP address.

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-kubernetes#1915]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Hi,
I am trying to run the following code:

```python
monitoring = kubernetes.helm.v3.Release(
    "monitoring",
    name="monitoring",
    chart="kube-prometheus-stack",
    namespace="monitoring",
    repository_opts=kubernetes.helm.v3.RepositoryOptsArgs(
        repo="https://prometheus-community.github.io/helm-charts",
    ),
    values={
        "grafana": {
            "ingress": {
                "enabled": True,
            },
        },
    },
)

grafana_ingress = kubernetes.networking.v1.Ingress.get(
    "grafana-ingress",
    Output.concat(monitoring.status.namespace, "/", monitoring.status.name, "-grafana"),
    opts=ResourceOptions(depends_on=[monitoring]),
)
grafana_ip = grafana_ingress.status.load_balancer.ingress[0].ip
```

And I get:
```console
$ pulumi up
...
kubernetes:networking.k8s.io/v1:Ingress (grafana-ingress):
    error: 2 errors occurred:
    	* Resource 'monitoring-grafana' was created but failed to initialize
    	* Ingress .status.loadBalancer field was not updated with a hostname/IP address.
        for more information about this error, see https://pulumi.io/xdv72s
```

I was monitoring the creation of ingress during the deployment. The `helm.v3.Release` waits for the creation of the `monitoring-grafana` ingress but the ingress itself got a public ip after 90 seconds. That's why it is failing.

@rawkode

**Comment by viveklak** [comment]
I am afraid as it stands this is more of a bug with Helm's await logic itself. This would likely replicate on the Helm CLI if you installed with await and tried to query the ingress.  We have talked about some of the limitations of `get` in the context of `getResource` for `v3.Chart` resource here: https://github.com/pulumi/pulumi-kubernetes/issues/1656 but I believe these issues apply more generally across providers. 

CC @mikhailshilkov and @lblackstone for input.

**Comment by yellowhat** [comment]
Is there a wrapper I can write?

I have tried:
```python
def get_ingress_ip(args):
    """Return Ingress ip"""

    ingress = args[0]
    for _ in range(10):
        ...
        sleep(5)

grafana_ingress = kubernetes.networking.v1.Ingress.get(
    "grafana-ingress",
    Output.concat(monitoring.status.namespace, "/", monitoring.status.name, "-grafana"),
)
grafana_ip = Output.all(grafana_ingress).apply(get_ingress_ip)
```

I am not sure how to check for the `ip` availability value.

**Comment by yellowhat** [comment]
May I ask which version are you running?

**Comment by Evan-S** [comment]
> May I ask which version are you running?

pulumi 3.5.1 and pulumi-kubernetes 3.4.1

If it is a helm issue as stated I'm not sure why versioning should matter, but this works for us without problem until we update.

**Comment by yellowhat** [comment]
Are you using `kubernetes.helm.v3.Chart` instead of `kubernetes.helm.v3.Release`?
Unfortunately I do not have a workaround for it.

**Comment by viveklak** [comment]
> 

OK this problem is really only applicable to helm release (which abdicates all chart deployment duties to Helm). Helm Chart will use Pulumi's await logic which has had significant improvements to handle such await scenarios. I would expect if you are running the latest Kubernetes provider. Are you seeing issues after upgrading to newer Kubernetes provider? Lets use a separate issue if so.

**Comment by yellowhat** [comment]
I wish was that simple:

```python
monitoring = kubernetes.helm.v3.Chart(
    "monitoring",
    kubernetes.helm.v3.ChartOpts(
        chart="kube-prometheus-stack",
        version="33.2.0",
        namespace=monitoring_ns.metadata.name,
        fetch_opts=kubernetes.helm.v3.FetchOpts(
            repo="https://prometheus-community.github.io/helm-charts",
        ),
        values={
            "grafana": {
                "ingress": {
                    "enabled": True,
                },
            },
        },
    ),
    opts=ResourceOptions(provider=k8s_provider),
)
```

```console
$ pulumi version
v3.25.1
$  pip list
Package           Version
----------------- -----------
pulumi            3.25.1
pulumi-aws        4.38.0
pulumi-command    0.0.3
pulumi-gcp        6.14.0
pulumi-kubernetes 3.16.0
...
$  pulumi up --yes 
Previewing update (dev):
     Type                             Name           Plan       Info
     pulumi:pulumi:Stack              gcp-gke-dev               3 errors; 2 messages
 +   ├─ kubernetes:helm.sh/v3:Chart   monitoring     create     
 +   ├─ gcp:dns:ManagedZone           dns-zone       create     
 +   ├─ gcp:dns:RecordSet             ps-dev-record  create     
 +   └─ kubernetes:core/v1:Namespace  monitoring-ns  create     
 
Diagnostics:
  pulumi:pulumi:Stack (gcp-gke-dev):
    Fetching cluster endpoint and auth data.
    kubeconfig entry generated for cluster.
 
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
        return future.result()
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 685, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 172, in serialize_properties
        result = await serialize_property(
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 343, in serialize_property
        value = await serialize_property(
      File "/usr/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 326, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 169, in run
        value = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 123, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 206, in run
        return await transformed.future(with_unknowns=True)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 123, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 206, in run
        return await transformed.future(with_unknowns=True)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 123, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 169, in run
        value = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 447, in gather_futures
        return await asyncio.gather(*value_futures_list)
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 123, in get_value
        val = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 169, in run
        value = await self._future
      File "/usr/lib/python3.10/site-packages/pulumi/output.py", line 194, in run
        transformed: Input[U] = func(value)
      File "/usr/lib/python3.10/site-packages/pulumi_kubernetes/yaml/yaml.py", line 543, in <lambda>
        CustomResourceDefinition(f"{x}", opts, **obj)))]
      File "/usr/lib/python3.10/site-packages/pulumi_kubernetes/apiextensions/v1/CustomResourceDefinition.py", line 126, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
    TypeError: CustomResourceDefinition._internal_init() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
```

`kubernetes.helm.v3.Release` as least allows me to deploy.
I think that `got an unexpected keyword argument 'status'` is a know problem for pulumi.

**Comment by yellowhat** [comment]
I am trying to implement a way to wait for the `ip` to be available:

```python
def get_ingress_ip(args):
    """Return Ingress ip"""

    ingress = args[0]
    for _ in range(10):
        ...
        sleep(5)

grafana_ingress = kubernetes.networking.v1.Ingress.get(
    "grafana-ingress",
    Output.concat(monitoring.status.namespace, "/", monitoring.status.name, "-grafana"),
)
grafana_ip = Output.all(grafana_ingress).apply(get_ingress_ip)
```

I am not sure how to check for the `ip` availability value.

**Comment by blampe** [comment]
Traefik doesn't update the `status` field by default -- you'll need to explicitly enable that behavior by passing something like 
* `--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1` or
* `--providers.kubernetesingress.ingressendpoint.hostname=localhost`  

I was able to reproduce this interaction with Pulumi and confirmed that setting ip/hostname allows everything to complete as expected.
 
See also https://github.com/traefik/traefik/issues/2173 and the docs [here](https://doc.traefik.io/traefik/providers/kubernetes-ingress/#ingressendpoint).

**Comment by LockedThread** [comment]
This is still happening using grafana-mimir bitnami helm chart.

Config:
```gateway: {
                        service: {
                            type: 'LoadBalancer',
                        },
                        ingress: {
                            enabled: true,
                        }
                    }```

**Comment by RamonGal** [comment]
I essentially got this same problem using the aws-load-balancer-controller helm chart to build application load balancers for services created by helm charts, when using Nodeports it never works and always waits indefinitely for the LB status, setting the pulumi wait to false crashes it also and requires manually removing the finalizers.

This is by no means a complete fix but it might help someone else.

I managed a workaround that works 1/2 of the time for some reason, where the wait period before querying the ip is slower when we use ClusterIPs for the service and "alb.ingress.kubernetes.io/target-type": "ip":

using Pulumi I get :
`import {
  ProviderResource,
  ComponentResource,
  Resource,
  Output,
} from "@pulumi/pulumi";
import { helm } from "@pulumi/kubernetes";

interface AlbControllerArgs {
  provider: ProviderResource | undefined;
  clusterName: Output<string>;
  clusterNamespace: Output<string>;
  labels: { [key: string]: string };
  version: string;
  vpcId: Output<string>;
  region: string;
  dependsOn?: Resource[];
}

class AlbController extends ComponentResource {
  public albController: Output< string >;
  constructor(name: string, args: AlbControllerArgs) {
    super("cluster-components:AlbController", name);

    const provider = args.provider;
    const clusterName = args.clusterName;
    const labels = args.labels;
    const version = args.version;
    const dependsOn = args.dependsOn;
    const clusterNamespace = args.clusterNamespace;
    const vpcId = args.vpcId;
    const region = args.region;
    // Define our aws ingress ctlr. Helm Release
    const albController = new helm.v3.Release(
      `${name}`,
      {
        namespace: clusterNamespace,
        chart: "aws-load-balancer-controller",
        version: version,
        repositoryOpts: { repo: "https://aws.github.io/eks-charts" },
        values: {
          clusterName: clusterName,
          vpcId:  vpcId,
          region:  region,
          nodeSelector: labels,
          serviceAnnotations: {
            "service.beta.kubernetes.io/aws-load-balancer-target-node-labels": `workload=${labels.workload}`,
          },
        },
      },
      {
        provider: provider,
        dependsOn: dependsOn,
        parent: this,
      },
    );
    this.albController = albController.name;
  }
}

export { AlbController };
`

then for the ingress i use:
`import {
  ProviderResource,
  ComponentResource,
  Resource,
  Output,
} from "@pulumi/pulumi";

import { albSecurityGroupId } from "../config";
import * as k8s from "@pulumi/kubernetes";

interface AlbArgs {
  provider: ProviderResource | undefined;
  services: {
    name: string;
    port: number;
    path: string;
  }[];
  clusterNamespace: Output<string>;
  labels: { [key: string]: string }; 
  subnetIds: Output<string[]>;
  dependsOn?: Resource[];
}

class AlbResource extends ComponentResource {
  public url: Output<string>;
  constructor(name: string, args: AlbArgs) {
    super("cluster-components:AlbController", name);

    const provider = args.provider;
    const services = args.services;
    const dependsOn = args.dependsOn; 
    const clusterNamespace = args.clusterNamespace;
    const subnetIds = args.subnetIds;

    const ingress = new k8s.networking.v1.Ingress(
      "alb-ingress",
      {
        metadata: {
          namespace: clusterNamespace,
          annotations: {
            "kubernetes.io/ingress.class": "alb",
            "alb.ingress.kubernetes.io/scheme": "internet-facing", 
            "alb.ingress.kubernetes.io/target-type": "ip",
            "alb.ingress.kubernetes.io/security-groups": albSecurityGroupId, 
            "alb.ingress.kubernetes.io/subnets": subnetIds.apply((ids) => {
              return ids.join(",");
            }),
          },
        },
        spec: { 
          ingressClassName: "alb",
          defaultBackend: {
            service: {
              name: services[0].name,
              port: {
                number: services[0].port,
              },
            },
          },
          rules: [
            {
              http: {
                paths: services.map((service) => {
                  return {
                    path: service.path,
                    pathType: "Prefix",
                    backend: {
                      service: {
                        name: service.name,
                        port: {
                          number: service.port,
                        },
                      },
                    },
                  };
                }, {}),
              },
            },
          ],
        },
      },
      { provider: provider, dependsOn: dependsOn },
    );

    this.url = ingress.status.loadBalancer.ingress[0].hostname;
  }
}

export { AlbResource };
`

if you only require maintenance to the ingress/LB, the target groups are updated normally so this works better in CI/CD for updates, but for the first run of pulumi up  it is better to run it by hand.

**Comment by EronWright** [comment]
Note that the docs do mention how to customize the timeout to "wait longer".  Possible resolutions to this issue include:
1. better await logic
2. better error message (e.g. suggesting the use of a custom timeout)
3. better docs

**Comment by Evan-S** [comment]
Actually, the issue on my end was caused by ingress-nginx. After updating that component and following the new way of designating a load balancer handled by that chart the loadBalancer field was correctly being updated. 

If you're using ingress-nginx in your stack I would check there for issues, but otherwise disregard my account of this issue.
