### ISSUE TITLE
can't create rolebinding - consistent error  module 'pulumi_kubernetes.rbac.v1' has no attribute 'Rolebinding'

### ISSUE THREAD

**Issue by singularit-io** [pulumi/pulumi-kubernetes#1988]
### Problem description

Code below provides all what is required to repro.

I create the cluster successfully, I create the namespace successfully, proving my provider works fine. BUT I can't create rolebinding.

It consistently complains about module 'pulumi_kubernetes.rbac.v1' has no attribute 'Rolebinding'

This is a showstopper, I really need that rolebinding created 
[repro_rolebinding_fail.zip](https://github.com/pulumi/pulumi-kubernetes/files/8713378/repro_rolebinding_fail.zip)
programmatically to manage access to the cluster the gitops way.

######## main contents #########
import pulumi
from pulumi_kubernetes.meta.v1 import ObjectMetaArgs
from pulumi_kubernetes.rbac.v1 import SubjectArgs, RoleRefArgs
import pulumi_eks as eks
import pulumi_kubernetes as k8s
from pulumi import ResourceOptions

eks_cluster = eks.Cluster(
    'eks-cluster',
)

cluster_args = eks.ClusterArgs(
    min_size=1,
    max_size=3,
    desired_capacity=1,
    instance_type='r6gd.large',
    version='1.23',
)

kubeconfig = eks_cluster.kubeconfig

provider = k8s.Provider('eks_cluster', k8s.ProviderArgs(kubeconfig=kubeconfig))

k8s.core.v1.Namespace(resource_name='ce-dev', opts=ResourceOptions(provider=provider))

k8s.rbac.v1.Rolebinding(resource_name='repro-binding',
                        metadata=ObjectMetaArgs(
                            name="gitops-admin",
                            namespace='ce-dev'),
                        subjects=SubjectArgs(
                                [{'kind': 'User', 'name': 'whatever'}]),
                        role_ref=RoleRefArgs(
                            api_group='rbac.authorization.k8s.io',
                            kind='Cluster',
                            name='admin'),
                        opts=ResourceOptions(provider=provider))
######### requirements.txt contents ###########
pulumi>=3.0.0,<4.0.0
pulumi-aws>=5.0.0,<6.0.0
pulumi-kubernetes>=3.0.0
pulumi_eks>=0.40.0
### Errors & Logs

error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/pulumi/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/lib/python3.9/runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/builds/singularit4/iac/pulumi/aws/mfa/cicd/./__main__.py", line 33, in <module>
        k8s.rbac.v1.Rolebinding(resource_name='repro-binding',
    AttributeError: module 'pulumi_kubernetes.rbac.v1' has no attribute 'Rolebinding'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

### Affected product version(s)

see requirements.txt for details

### Reproducing the issue

provided below files or above code snippets allow repro with ease, deploying EKS, then the namespace, then the rolebinding issue

### Suggestions for a fix

None ATM, earlier pulumi-kubernetes version of package shows the same errors.

Also tried with k8s.rbac.v1.Rolebinding

**Comment by guineveresaenger** [comment]
Hi @singularit-io - I believe this is a capital B in `RoleBinding`: https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/rbac/v1/RoleBinding.py#L103

Hope that gets you unstuck!
