### ISSUE TITLE
[java] helm release installation fails: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by hnicke** [pulumi/pulumi-kubernetes#2209]
### What happened?

I get an `Index 0 out of bounds for length 0` error when trying to provision a helm chart with the java sdk.

### Steps to reproduce

```java
    private val ingressController = Release(
        "nginx-ingress-controller",
        ReleaseArgs.builder()
            .chart("ingress-nginx")
            .version("4.1.4")
            .namespace(nginxNamespace)
            .repositoryOpts(
                RepositoryOptsArgs.builder()
                    .repo("https://kubernetes.github.io/ingress-nginx")
                    .build()
            )
            .build(),
    )
```

With above Release resource defined in the stack, run `pulumi up`

### Expected Behavior

No error.

### Actual Behavior

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.set(ArrayList.java:441)
        at com.google.protobuf.LazyStringArrayList.set(LazyStringArrayList.java:140)
        at com.google.protobuf.LazyStringArrayList.set(LazyStringArrayList.java:61)
        at pulumirpc.Resource$ReadResourceRequest$Builder.setDependencies(Resource.java:3384)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadResource.lambda$readResourceAsync$1(DeploymentImpl.java:1345)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at com.pulumi.resources.Resource$LazyField.complete(Resource.java:608)
        at com.pulumi.resources.Resource$LazyField.completeOrThrow(Resource.java:601)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$0(DeploymentImpl.java:1166)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
    error: an unhandled error occurred: '.... run --console=plain' exited with non-zero exit code: 1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @hnicke, thank you for reporting this issue! Could you please submit the full definition of the stack for us to further investigate the problem?

**Comment by hnicke** [comment]
I can't share the complete stack unfortunately.
I tried to compile a minimal example. However, I can't reproduce the error since I'm getting another one now.
I've reported the new problem here: https://github.com/pulumi/pulumi-java/issues/629#issuecomment-128669751

Closing this issue for now.
