### ISSUE TITLE
Cannot create a ConfigMap with a data dict with Output in them

### ISSUE THREAD

**Issue by maelp** [pulumi/pulumi-kubernetes#2327]
### What happened?

I'm trying to build a ConfigMap object to configure ingress-nginx, using objects where some might be `Output[str]` (for instance `t["namespace"]` in the following example)

```
    map = ConfigMap(
        "udp-services-configmap",
        metadata=ObjectMetaArgs(
            name="udp-services-configmap", namespace=ingress_nginx_ns.metadata.name
        ),
        # data is a mapping port: namespace/service:service_port
        data={
            t["port"]: Output.format(
                "{}/{}:{}", t["namespace"], t["service"], t["service_port"]
            )
            for t in services
        },
        opts=pulumi.ResourceOptions(
            provider=k8s_provider,
        ),
    )
```

When I do this I get an error like this

```
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 523, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 124, in prepare_resource
        serialized_props = await rpc.serialize_properties(
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 223, in serialize_properties
        struct[translated_name] = result
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 784, in __setitem__
        _SetStructValue(self.fields[key], value)
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 746, in _SetStructValue
        struct_value.struct_value.update(value)
      File "/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 820, in update
        _SetStructValue(self.fields[key], value)
    TypeError: bad argument type for built-in operation
```

I know the error comes from the `data` because if I comment it it works fine. Also `t["port"]` is a `str` in this example, and not a `Output[str]` (but I'd like to know how to do it too if it was an Output)

### Expected Behavior

I should be able to create the ConfigMap

### Steps to reproduce

See the description above

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME                      VERSION
docker                    3.1.0
gcp                       6.46.0
kubernetes                3.23.1
kubernetes-cert-manager   0.0.5
kubernetes-ingress-nginx  0.0.10
python                    unknown

Host     
OS       darwin
Version  13.0.1
Arch     x86_64

This project is written in python: executable='/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/bin/python3' version='3.10.9
'

Current Stack: maelp/infra-arch-pulumi/staging

TYPE                                                                       URN
pulumi:pulumi:Stack                                                        urn:pulumi:staging::infra-arch-pulumi::pulumi:pulumi:Stack::infra-arch-pulumi-staging
docker:image:Image                                                         urn:pulumi:staging::infra-arch-pulumi::docker:image:Image::web-app-image
pulumi:providers:gcp                                                       urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:gcp::gcp
pulumi:providers:gcp                                                       urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:gcp::default_6_46_0
pulumi:providers:kubernetes                                                urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:kubernetes::cluster
gcp:compute/address:Address                                                urn:pulumi:staging::infra-arch-pulumi::gcp:compute/address:Address::web-ingress-ip
pulumi:providers:kubernetes                                                urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:kubernetes::default_3_23_1
gcp:artifactregistry/repository:Repository                                 urn:pulumi:staging::infra-arch-pulumi::gcp:artifactregistry/repository:Repository::gcp-docker-repository
kubernetes:core/v1:Namespace                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Namespace::apps
kubernetes:core/v1:Namespace                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Namespace::ingress-nginx
kubernetes:core/v1:Namespace                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Namespace::cert-manager
kubernetes:core/v1:Secret                                                  urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Secret::gouach-server-certificate-secret
kubernetes:core/v1:Secret                                                  urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Secret::client-ca
kubernetes:core/v1:ConfigMap                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:ConfigMap::udp-services-configmap
kubernetes:helm.sh/v3:Chart                                                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart::ingress-nginx
kubernetes:helm.sh/v3:Chart                                                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart::cert-manager
kubernetes:cert-manager.io/v1:ClusterIssuer                                urn:pulumi:staging::infra-arch-pulumi::kubernetes:cert-manager.io/v1:ClusterIssuer::cert-manager-cluster-issuer
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::web-app-1
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::udp-53-app
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::web-app-2
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::udp-53
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::web-app-1-svc
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::web-app-2-svc
kubernetes:networking.k8s.io/v1:Ingress                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:networking.k8s.io/v1:Ingress::web-app-1-ingress-tls-letsencrypt
kubernetes:networking.k8s.io/v1:Ingress                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:networking.k8s.io/v1:Ingress::web-app-2-ingress-mtls
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager-cainjector
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager
kubernetes:core/v1:ConfigMap                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ConfigMap::cert-manager/cert-manager-webhook
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::cert-manager/cert-manager-webhook
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager-startupapicheck
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::ingress-nginx/ingress-nginx
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::ingress-nginx/ingress-nginx-controller-admission
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::ingress-nginx/ingress-nginx-controller
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::cert-manager/cert-manager
kubernetes:batch/v1:Job                                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:batch/v1:Job::ingress-nginx/ingress-nginx-admission-patch
kubernetes:core/v1:ConfigMap                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ConfigMap::ingress-nginx/ingress-nginx-controller
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::ingress-nginx/ingress-nginx-admission
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager-webhook
kubernetes:batch/v1:Job                                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:batch/v1:Job::cert-manager/cert-manager-startupapicheck
kubernetes:batch/v1:Job                                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:batch/v1:Job::ingress-nginx/ingress-nginx-admission-create
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::certificaterequests.cert-manager.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::orders.acme.cert-manager.io
kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration  urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration::cert-manager-webhook
kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration::cert-manager-webhook
kubernetes:networking.k8s.io/v1:IngressClass                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:networking.k8s.io/v1:IngressClass::nginx
kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration  urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration::ingress-nginx-admission
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::certificates.cert-manager.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::challenges.acme.cert-manager.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::clusterissuers.cert-manager.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-cainjector
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-issuers
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::issuers.cert-manager.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-orders
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-clusterissuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-edit
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-ingress-shim
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-clusterissuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-certificatesigningrequests
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-webhook:subjectaccessreviews
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-cainjector
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-certificates
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-issuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-certificates
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-challenges
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-orders
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-challenges
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-approve:cert-manager-io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-certificatesigningrequests
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-approve:cert-manager-io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-webhook:subjectaccessreviews
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-ingress-shim
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-view
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::ingress-nginx-admission
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::ingress-nginx-admission
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager-cainjector:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager-cainjector:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager-webhook:dynamic-serving
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager-webhook:dynamic-serving
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager-startupapicheck:create-cert
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager-startupapicheck:create-cert
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::ingress-nginx/ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::ingress-nginx/ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::ingress-nginx/ingress-nginx-admission
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::ingress-nginx/ingress-nginx-admission
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::cert-manager/cert-manager-cainjector
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::cert-manager/cert-manager
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::cert-manager/cert-manager-webhook
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::ingress-nginx/ingress-nginx-controller

Found no pending operations associated with staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/maelp
User           maelp
Organizations  maelp

Dependencies:
NAME                             VERSION
pip                              23.0.0
pulumi-docker                    3.1.0
pulumi-gcp                       6.46.0
pulumi-kubernetes-cert-manager   0.0.5
pulumi-kubernetes-ingress-nginx  0.0.10
setuptools                       66.0.0
wheel                            0.38.4

Pulumi locates its logs in /var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maelp** [comment]
Found the issue, I should have used `str(t["port"])` ;)
