### ISSUE TITLE
Nil pointer dereference when `pulumi destroy -r`

### ISSUE THREAD

**Issue by archisgore** [pulumi/pulumi-kubernetes#233]
I was running `pulumi destroy -r` because some of my resources were partly deleted and timed out.

Led to this:
```
Diagnostics:
  pulumi:pulumi:Stack: aws-ts-eks-pulumi-stack-polyverse-dot-com
    info: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e51326]
    goroutine 15 [running]:
    github.com/pulumi/pulumi-kubernetes/pkg/provider.checkpointObject(0xc4200aa778, 0x0, 0xc4202c74c0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:750 +0x26
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).Read(0xc4202f4000, 0x2b1c7e0, 0xc4204233e0, 0xc4202bf810, 0xc4202f4000, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:505 +0x511
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Read_Handler.func1(0x2b1c7e0, 0xc4204233e0, 0x20b23a0, 0xc4202bf810, 0x2b1c7e0, 0xc4204233e0, 0x2b221c0, 0x2bb72a0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1247 +0x86
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2b1c7e0, 0xc4204233e0, 0x20b23a0, 0xc4202bf810, 0xc42048fc20, 0xc42048fc40, 0x0, 0x0, 0x2afca60, 0xc42034cd70)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Read_Handler(0x20b91c0, 0xc4202f4000, 0x2b1c7e0, 0xc4202ed740, 0xc4202bf7c0, 0xc420151460, 0x0, 0x0, 0x199, 0x10b9df9)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1249 +0x16d
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202f2000, 0x2b20080, 0xc420282000, 0xc420306200, 0xc420422150, 0x2b88f38, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202f2000, 0x2b20080, 0xc420282000, 0xc420306200, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202da060, 0xc4202f2000, 0x2b20080, 0xc420282000, 0xc420306200)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:570 +0xa1
 
  kubernetes:certmanager.k8s.io:Issuer: prod-lets-encrypt-issuer
    error: Preview failed: transport is closing
 
  kubernetes:certmanager.k8s.io:Issuer: staging-lets-encrypt-issuer
    error: Preview failed: transport is closing
 
error: an error occurred while advancing the preview
```

**Comment by hausdorff** [comment]
Fixed in https://github.com/pulumi/pulumi-kubernetes/pull/221

**Comment by hausdorff** [comment]
Because this came up twice, we've cut `v0.17.1`. The release script is running now. Check back in about 10 minutes and should be able to use the fix.
