### ISSUE TITLE
Using `inspect.getfullargspec` in pulumi_kubernetes `_parse_yaml_object` returns "wrong" function signature for a class method.

### ISSUE THREAD

**Issue by Kody-Quintana** [pulumi/pulumi-kubernetes#2468]
### What happened?

With Python, using a class method as a transformation with `pulumi_kubernetes.yaml.ConfigFile` fails with the following:
```
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/home/user/my_project/__main__.py", line 430, in <module>
    _main()
  File "/home/user/my_project/__main__.py", line 405, in _main
    k8s.yaml.ConfigFile(
  File "/home/user/.local/lib/python3.11/site-packages/pulumi_kubernetes/yaml/yaml.py", line 353, in __init__
    self.resources = _parse_yaml_document(__ret__, opts, transformations, resource_prefix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pulumi_kubernetes/yaml/yaml.py", line 421, in _parse_yaml_document
    file_objects = _parse_yaml_object(obj, opts, transformations, resource_prefix)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pulumi_kubernetes/yaml/yaml.py", line 450, in _parse_yaml_object
    t(obj, opts)
TypeError: MyClass.my_class_method() takes 2 positional arguments but 3 were given
```
Specifically the [code here](https://github.com/pulumi/pulumi-kubernetes/blob/96af747c1510ee5bf038845b46a8f369842f7090/sdk/python/pulumi_kubernetes/yaml/yaml.py#L446-L452) from `pulumi-kubernetes/sdk/python/pulumi_kubernetes/yaml/yaml.py
`:
```python
# Allow users to change API objects before any validation.
if transformations is not None:
    for t in transformations:
        if len(getfullargspec(t)[0]) == 2:
            t(obj, opts)
        else:
            t(obj)
```
does not handle class methods correctly.

### Expected Behavior

The number of args should take into account whether or not `t` is a method.

### Steps to reproduce

Here is a minimal working example of a class that I'm trying to use a class method from:
```python
from collections import UserDict

class MyClass(UserDict):

    def __init__(self, additional_tags=None):
        super().__init__()
        # Do something to populate self.data here to use for tags

        if additional_tags is not None:
            self.data.update(additional_tags)

    @classmethod
    def add_k8s_annotations(cls, obj):
        """For use with pulumi_kubernetes.yaml.ConfigFile transformations.
        This class method adds the MyClass tags dict to a k8s config file"""

        # Ensure that metadata.annotations exists
        if obj.get('metadata') is None:
            obj['metadata'] = {}
        if obj['metadata'].get('annotations') is None:
            obj['metadata']['annotations'] = {}

        # add the values from a new instance of this class to the annotations dict
        obj['metadata']['annotations'] = cls(obj['metadata']['annotations'])
```
Then usage of the class:
```python
pulumi_kubernetes.yaml.ConfigFile(
    "my-k8s-thing",
    file="./my-k8s-thing.yaml",
    transformations=[
        MyClass.add_k8s_annotations
    ]
)
```

### Output of `pulumi about`

```
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.41.0
kubernetes  3.29.0
linode      3.12.0
python      unknown
random      4.13.2

Host
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.11.3'

(stack omitted)

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/Kody-Quintana
User           Kody-Quintana
Organizations  Kody-Quintana
```

### Additional context

I can just use a function with the correct signature to call my class method instead of calling it directly, so I'll do that for now, but if this could be handled correctly it'd be nice just so it's more clear what is being called

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ericnear** [comment]
+1
