### ISSUE TITLE
Nginx Ingress no longer installs in v3.Release

### ISSUE THREAD

**Issue by awopenphone** [pulumi/pulumi-kubernetes#2684]
### What happened?

Running pulumi up on this code generates this Go language error every time:

```
const _ingresskNamespace = new k8s.core.v1.Namespace(
  'ingress',
  { metadata: { name: 'ingress' } },
  { provider: k8sProvider },
)

const _ingressNginxValues = new pulumi.asset.FileAsset('charts/ingress-nginx/values.yaml')
const _ingressNginxRelease = new helm.v3.Release(
  'ingress-nginx',
  {
    name: 'ingress-nginx',
    namespace: _ingresskNamespace.metadata.name,
    chart: 'ingress-nginx',
    repositoryOpts: { repo: 'https://kubernetes.github.io/ingress-nginx' },
    version: '4.8.3',
    valueYamlFiles: [_ingressNginxValues],
  },
  { provider: k8sProvider, dependsOn: [_ingresskNamespace] },
)
```

### Example
```
Diagnostics:
  kubernetes:helm.sh/v3:Release (ingress-nginx):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (dev-eks-dev-charts-system):
    panic: interface conversion: interface {} is map[interface {}]interface {}, not map[string]interface {}
    goroutine 301 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.excludeNulls({0x102a96c00?, 0x140032f7770?})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1402 +0x2d0
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.excludeNulls({0x102a94c80?, 0x140032f61b0?})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1412 +0x214
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.mergeMaps(0x140032f61b0, 0x140032f61e0?, 0x0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1389 +0xe4
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.decodeRelease(0x1023c1e51?, {0x140019fdd80, 0x80})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:316 +0x338
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*helmReleaseProvider).Check(0x140027da600, {0x102ebd1b0, 0x140032f6000}, 0x14005d00de0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:359 +0x3ac
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).Check(0x14000561200, {0x102ebd1b0, 0x140032f6000}, 0x14005d00de0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1295 +0xfb8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x102ebd1b0, 0x140032f6000}, {0x102cc5940?, 0x14005d00de0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.92.0/proto/go/provider_grpc.pb.go:557 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x102ebd1b0, 0x140032cfe30}, {0x102cc5940, 0x14005d00de0}, 0x1400051afc0, 0x140032a9c08)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x102e1e0c0?, 0x14000561200}, {0x102ebd1b0, 0x140032cfe30}, 0x140032804d0, 0x14000888860)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.92.0/proto/go/provider_grpc.pb.go:559 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140008343c0, {0x102ecb3e0, 0x14000a6e000}, 0x140032eb9e0, 0x14000891020, 0x1046a9830, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1376 +0xb44
    google.golang.org/grpc.(*Server).handleStream(0x140008343c0, {0x102ecb3e0, 0x14000a6e000}, 0x140032eb9e0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1753 +0x7c4
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:998 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 100
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:996 +0x154
```
```
### Output of `pulumi about`

❯ pulumi about 
CLI          
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.7.0
aws         5.31.0
awsx        2.1.0
datadog     4.23.0
docker      4.4.4
docker      3.6.1
eks         1.0.4
flux        1.0.1
kubernetes  4.5.4
kubernetes  3.30.2
nodejs      unknown

Host     
OS       darwin
Version  14.1.2
Arch     arm64

Dependencies:
NAME                              VERSION
@pulumi/eks                       1.0.4
@pulumi/pulumi                    3.94.2
@types/jest                       29.5.7
ts-node                           10.9.1
@pulumi/awsx                      2.1.0
@pulumi/datadog                   4.23.0
jest                              29.7.0
typescript                        5.2.2
@pulumi/kubernetes                4.5.4
@worawat/flux                     1.0.1
@pulumi/aws                       6.7.0
@swc/core                         1.3.95
@swc/jest                         0.2.29
@types/js-yaml                    4.0.8
@types/node                       20.8.10
eslint-plugin-simple-import-sort  10.0.0
@openphone/eslint-config-node     1.3.13
@openphone/helpers                6.4.10
js-yaml                           4.1.0
ts-jest                           29.1.1
@jest/types                       29.6.3
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for reporting this @awopenphone. We'll take a look. 

I made a repro project here: https://github.com/mjeffryes/nodejs-repros/tree/pulumi-kubernetes-2684, but unfortunately, it does not trigger the panic you're seeing. (Probably the panic is triggered when processing state from your cluster.)

Link to the line number from the stack trace: https://github.com/pulumi/pulumi-kubernetes/blob/1944a5215b0e12b373547393a6294ef0aee60c28/provider/pkg/provider/helm_release.go#L1402C3-L1402C3

**Comment by awopenphone** [comment]
I am also able to recreate this still with botht he ofifical chart and the bitnami chart:

```
     └─ kubernetes:helm.sh/v3:Release  ingress-nginx                         1 error

Diagnostics:
  kubernetes:helm.sh/v3:Release (ingress-nginx):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (infra-eks-system-charts-dev):
    panic: interface conversion: interface {} is map[interface {}]interface {}, not map[string]interface {}
    goroutine 188 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.excludeNulls({0x104d79c00?, 0x1400518c450?})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1402 +0x2d0
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.excludeNulls({0x104d77c80?, 0x140015bfec0?})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1412 +0x214
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.mergeMaps(0x140015bfec0, 0x140015bfef0?, 0x0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:1389 +0xe4
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.decodeRelease(0x1046a5df1?, {0x14001bfd5f0, 0x82})
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:316 +0x338
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*helmReleaseProvider).Check(0x14001448f00, {0x10519a310, 0x140015bfd10}, 0x1400e180900)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/helm_release.go:359 +0x3ac
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).Check(0x140006ce480, {0x10519a310, 0x140015bfd10}, 0x1400e180900)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1295 +0xfb8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x10519a310, 0x140015bfd10}, {0x104fa2f80?, 0x1400e180900})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.92.0/proto/go/provider_grpc.pb.go:557 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10519a310, 0x140015bfb60}, {0x104fa2f80, 0x1400e180900}, 0x14000945680, 0x14005180630)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x1050fb240?, 0x140006ce480}, {0x10519a310, 0x140015bfb60}, 0x140015aa1c0, 0x140009909e0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.92.0/proto/go/provider_grpc.pb.go:559 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400021c3c0, {0x1051a8540, 0x14000103380}, 0x14001385680, 0x14000a857d0, 0x106985830, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1376 +0xb44
    google.golang.org/grpc.(*Server).handleStream(0x1400021c3c0, {0x1051a8540, 0x14000103380}, 0x14001385680, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1753 +0x7c4
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:998 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 88
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:996 +0x154
```

```
const _ingressNginxRelease = new helm.v3.Release(
  'ingress-nginx',
  {
    name: 'ingress-nginx',
    namespace: _ingressNamespace.metadata.name,
    chart: 'ingress-nginx',
    repositoryOpts: { repo: 'https://charts.bitnami.com/bitnami' },
    version: '15.4.4',
    valueYamlFiles: [_ingressNginxValues],
  },
  { provider: k8sProvider, dependsOn: [_ingressNamespace, _ingressCrds] },
)
```

**Comment by rquitales** [comment]
@awopenphone Are you able to provide the contents of the values file (`_ingressNginxValues`)?
