### ISSUE TITLE
Pulumi up gives error: Program failed with an unhandled exception

### ISSUE THREAD

**Issue by KurtOps** [pulumi/pulumi-kubernetes#2806]
### What happened?

After upgrading to the latest version of `pulumi` and `kubectl`, running `pulumi up` results in the exception below. Additional error details are below:

`
status = StatusCode.UNKNOWN
    	details = "Failed to parse kubectl version JSON output. Received: "
    	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-01T11:10:54.193628-05:00", grpc_status:2, grpc_message:"Failed to parse kubectl version JSON output. Received: "}"
    >
`

### Example

`pulumi:pulumi:Stack (aws-eks-3-test):
    Error: Failed to parse kubectl version JSON output. Received: : Error: Failed to parse kubectl version JSON output. Received:
        at assertCompatibleKubectlVersionExists (/snapshot/eks/bin/dependencies.js:46:15)
        at createCore (/snapshot/eks/bin/cluster.js:211:61)
        at createCluster (/snapshot/eks/bin/cluster.js:800:18)
        at new ClusterInternal (/snapshot/eks/bin/cluster.js:879:25)
        at Object.construct (/snapshot/eks/bin/cmd/provider/cluster.js:21:29)
        at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:131:24)
        at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)
        at Generator.next (<anonymous>)
        at fulfilled (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
`

### Output of `pulumi about`

CLI
Version      3.104.2
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.18.2
awsx        2.4.0
docker      4.5.1
eks         2.0.0-alpha.4
kubernetes  4.7.1
python      unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.12/bin/python3' version='3.12.1'

Current Stack: 

Found no resources associated with test

Found no pending operations associated with test

Backend
Name           pulumi.com
URL            https://app.pulumi.com/KurtOps
User           KurtOps
Organizations  KurtOps
Token type     personal

Pulumi locates its logs in /var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: illegal semver returned by language host: pulumi_eks@2.0.0a4: Invalid character(s) found in patch number "0a4"

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thank you for the bug report @KurtOps; The error message is not the most clear, but it generally means that we're not able to interpret the out put from `kubectl version`. Would you mind posting the output of `kubectl version` here?

FWIW I noticed you're also on an alpha version of the eks plugin. You might want to update to point at the latest release version.

**Comment by KurtOps** [comment]
Thanks for the response. Here's the kubectl version:

```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

**Comment by KurtOps** [comment]
@mjeffryes what's controlling the version of the eks plugin? seems to always want to pull the a4 version even though I see the newer `2.2.1` version is latest. Thanks.

**Comment by mjeffryes** [comment]
@KurtOps The plugin version is derived from the version of the SDK you're using for that package, so if you upgrade the python package for eks to 2.2.1, you'll get the newer plugin.

WRT the kubectl error, I think the problem is that the format of `kubectl version` changed recently from a structured output to just the version string. EG. here is what my local `kubectl version` reports:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
```

There's even a warning in there about the format changing. We'll try to pick up a fix here soon. In the meantime, downgrading kubectl is probably your best option for a workaround.

**Comment by rquitales** [comment]
The error is originating from the `pulumi-eks` provider. Upon investigating this issue and examining the code at version 2.0.0-alpha.4, I've noticed that we are already specifying the output format option with `kubectl version --output=json` (reference: https://github.com/pulumi/pulumi-eks/blob/8e5c04b80044491d936e4690890b7ab4bc59f8a3/nodejs/eks/dependencies.ts#L43C53-L43C82). Therefore, the change in the output format of `kubectl version` is not the root cause of this problem.

Based on the provided original error message, it seems that the output obtained from `kubectl version --output=json` is only `"}"`. It appears that the provider did not completely capture the entire stdout of the `kubectl version` command correctly, leading to a parsing error. The cause of this issue is unclear, as I am unable to reproduce it on my end using either v2.0.0-alpha.4 or the latest v2.2.1 of the EKS provider. I am also using the latest versions of Pulumi CLI (v3.104.2) and kubectl (v1.29.1 - installed via Homebrew on MacOS).

There is a possibility that a formatting error is occurring here when attempting to retrieve the current API server's version, which is unnecessary for our EKS provider. We addressed this by updating the command to only fetch the client version in v2.2.0 of the EKS provider.

@KurtOps, could you try updating the version of the EKS provider to see if this resolves your issue? Alternatively, it might be a transient error with `kubectl`, so does re-running `pulumi up` succeed? Regardless, we strongly recommend upgrading to the latest EKS provider to benefit from the latest improvements we have shipped. For example, you can do so by updating your `requirements.txt` to specify `pulumi-eks>=2.0.0,<3.0.0` instead of `pulumi-eks==2.0.0a4` and running `source venv/bin/activate; pip install -r requirements.txt`.

I am downgrading this from a P1 as the issue isn't as far reaching as we initially suspected.
