### ISSUE TITLE
Computed inputs to `Secret` cause a panic

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes#2845]
### Problem description

Given a program with a `Secret` resource that contains a computed value, the preview panics.

### Errors & Logs

```
Diagnostics:
  pulumi:pulumi:Stack (vision-proteus-592709):
    panic: cannot deep copy resource.Computed
    goroutine 142 [running]:
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x2351720?, 0xc00290add0?})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/runtime/converter.go:639 +0x21b
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x22aa400?, 0xc002715b30?})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/runtime/converter.go:623 +0x265
    k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/runtime/converter.go:608
    k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedMap(0x1?, {0xc001eef168?, 0xc001eef1d8?, 0xba7f0f?})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.0/pkg/apis/meta/v1/unstructured/helpers.go:189 +0x34
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/clients.normalizeSecretData(0xc002ea4108)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/clients/unstructured.go:149 +0x55
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/clients.normalizeSecret(0xc002ea4108)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/clients/unstructured.go:120 +0x248
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/clients.Normalize(0x2521420?)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/clients/unstructured.go:75 +0xc5
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.normalizeInputs(0xc002ea4108)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2751 +0x8f
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).Check(0xc000529b00, {0x2aec338, 0xc0027156b0}, 0xc0025de600)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1339 +0x5a8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x2aec338, 0xc0027156b0}, {0x24d5480?, 0xc0025de600})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.96.2/proto/go/provider_grpc.pb.go:557 +0x72
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x2aec338, 0xc002714ea0}, {0x24d5480, 0xc0025de600}, 0xc00160b700, 0xc0028ac840)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x262e9e0?, 0xc000529b00}, {0x2aec338, 0xc002714ea0}, 0xc001f931f0, 0xc000917220)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.96.2/proto/go/provider_grpc.pb.go:559 +0x135
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009c83c0, {0x2afaa20, 0xc000007520}, 0xc002ef85a0, 0xc00079d500, 0x438ea50, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
    google.golang.org/grpc.(*Server).handleStream(0xc0009c83c0, {0x2afaa20, 0xc000007520}, 0xc002ef85a0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 55
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x145

```

### Affected product version(s)

```
NAME           KIND      VERSION  SIZE    INSTALLED    LAST USED
aws            resource  6.13.1   557 MB  1 month ago  11 minutes ago
command        resource  0.9.2    34 MB   1 month ago  11 minutes ago
datadog        resource  4.23.0   74 MB   1 month ago  11 minutes ago
docker         resource  4.5.0    49 MB   1 month ago  11 minutes ago
gcp            resource  7.6.0    207 MB  4 weeks ago  11 minutes ago
gcp            resource  6.67.1   178 MB  1 month ago  11 minutes ago
github         resource  5.22.0   60 MB   1 month ago  11 minutes ago
kubernetes     resource  4.6.1    94 MB   1 month ago  11 minutes ago
mysql          resource  3.2.0    55 MB   1 month ago  11 minutes ago
port           resource  1.6.0    40 MB   1 month ago  11 minutes ago
postgresql     resource  3.10.0   47 MB   1 month ago  11 minutes ago
pulumiservice  resource  0.16.0   34 MB   1 month ago  11 minutes ago
random         resource  4.14.0   37 MB   1 month ago  11 minutes ago

```

### Reproducing the issue

```yaml
name: issue-2846
runtime: yaml
description: Unknown values in secrets
variables: {}
outputs:
  password: ${prefix.id}
resources:
  prefix:
    type: random:RandomPet
  my-secret:
    type: kubernetes:core/v1:Secret
    properties:
      metadata:
        name: my-secret
      data:
        username: dXNlcm5hbWU= # base64 encoded "username"
        password:
          fn::toBase64: ${prefix.id}
```

**Comment by EronWright** [comment]
Reference: [Slack discussion](https://pulumi.slack.com/archives/C05NN2SC97S/p1708627240295689)
