### ISSUE TITLE
TypeError: Union[arg, ...]: each arg must be a type. Got <property object at 0x10d377dd0>.

### ISSUE THREAD

**Issue by xiaowww1992** [pulumi/pulumi-kubernetes#3161]
### What happened?

Traceback (most recent call last):
  File "/Users/xiaozhijian/Desktop/streamflow/manage.py", line 22, in <module>
    main()
  File "/Users/xiaozhijian/Desktop/streamflow/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 96, in handle
    self.run(**options)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 638, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 623, in start_django
    reloader.run(django_main_thread)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 329, in run
    self.run_loop()
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 335, in run_loop
    next(ticker)
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 375, in tick
    for filepath, mtime in self.snapshot_files():
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 391, in snapshot_files
    for file in self.watched_files():
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 289, in watched_files
    yield from iter_all_python_module_files()
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 115, in iter_all_python_module_files
    modules = tuple(m for m in map(sys.modules.__getitem__, keys) if not isinstance(m, weakref.ProxyTypes))
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 115, in <genexpr>
    modules = tuple(m for m in map(sys.modules.__getitem__, keys) if not isinstance(m, weakref.ProxyTypes))
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/pulumi/_utils.py", line 286, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/pulumi_kubernetes/resource/v1alpha2/__init__.py", line 8, in <module>
    from .PodSchedulingContext import *
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/pulumi_kubernetes/resource/v1alpha2/PodSchedulingContext.py", line 18, in <module>
    from ._inputs import *
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/pulumi_kubernetes/resource/v1alpha2/_inputs.py", line 492, in <module>
    class NamedResourcesAttributePatchArgs:
  File "/Users/xiaozhijian/Desktop/streamflow/venv/lib/python3.10/site-packages/pulumi_kubernetes/resource/v1alpha2/_inputs.py", line 539, in NamedResourcesAttributePatchArgs
    def bool(self, value: Optional[pulumi.Input[bool]]):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 1081, in __getitem__
    return self.copy_with(tuple(new_args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 1240, in copy_with
    return Union[params]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 403, in __getitem__
    return self._getitem(self, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 515, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 515, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got <property object at 0x10d377dd0>.

### Example

import pulumi_kubernetes as k8s
from pulumi import automation as auto

# Create a stack using the local Pulumi program
stack = auto.create_or_select_stack(stack_name="dev")

### Output of `pulumi about`

none

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@xiaowww1992 can you please include the output of `pulumi about`? That should capture the library versions you're using.

**Comment by mrafayaleem** [comment]
Can you try disabling the django auto reload using `python manage.py runserver --noreload`? That helped fix this issue for me.
