### ISSUE TITLE
pulumi binray panic when I run pulumi preview:  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by loveRhythm1990** [pulumi/pulumi-kubernetes#3168]
### What happened?

I run pulumi binary in my **mac** desktop, it always panics.

```
lr90@sj cs-component % KUBECONFIG=/path/to/kubeconfig pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/OurOrg/cs-component/dev/previews/396c7338-33a2-4c44-8f68-1e0b38e587e9

     Type                            Name              Plan     Info
     pulumi:pulumi:Stack             cs-component-dev           22 messages
     └─ pulumi:providers:kubernetes  kubernetes                 1 error

Diagnostics:
  pulumi:providers:kubernetes (kubernetes):
    error: rpc error: code = Unavailable desc = error reading from server: EOF

  pulumi:pulumi:Stack (cs-component-dev):

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdbc9251]
    goroutine 59 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).DiffConfig.func1()
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:399 +0x11
    github.com/pulumi/pulumi-kubernetes/provider/v4/pkg/provider.(*kubeProvider).DiffConfig(0x13046460?, {0xf3d2280?, 0x40?}, 0xc000416100)
        /home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:418 +0x9fb
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_DiffConfig_Handler.func1({0xf4c3e10?, 0xc000b847e0?}, {0xedf9260?, 0xc000416100?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.127.0/proto/go/provider_grpc.pb.go:522 +0xcb
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xf4c3e10, 0xc000b84450}, {0xedf9260, 0xc000416100}, 0xc0005fe160, 0xc0005fa528)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3db
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_DiffConfig_Handler({0xf3d2280, 0xc000452b60}, {0xf4c3e10, 0xc000b84450}, 0xc000416080, 0xc000c86620)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.127.0/proto/go/provider_grpc.pb.go:524 +0x143
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005de000, {0xf4c3e10, 0xc0006dc180}, {0xf51c160, 0xc00082c180}, 0xc0003698c0, 0xc000c8cd80, 0x13074708, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1379 +0xdf8
    google.golang.org/grpc.(*Server).handleStream(0xc0005de000, {0xf51c160, 0xc00082c180}, 0xc0003698c0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1790 +0xe8b
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1029 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1040 +0x125

```

### Example

NA

### Output of `pulumi about`

```
lr90@sj cs-component % pulumi about
CLI          
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
language  go          unknown
resource  kubernetes  4.17.0

Host     
OS       darwin
Version  14.5
Arch     x86_64


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ourorg
User           ourorg
Organizations  ourorg
Token type     personal

Dependencies:
NAME                                                VERSION
github.com/google/go-github/v58                     v58.0.0
github.com/ourorg/cloudsigma-gitops/csapi  
github.com/pulumi/pulumi-kubernetes/sdk/v4          v4.17.0
github.com/pulumi/pulumi/sdk/v3                     v3.129.0
sigs.k8s.io/yaml                                    v1.4.0

```

### Additional context

our pipelines in github action seems work alright, it uses ubuntu.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@loveRhythm1990 is this an existing stack? Can you share what your code looks like? Are you configuring your provider with the new `clusterIdentifier` config?

**Comment by loveRhythm1990** [comment]
> [@loveRhythm1990](https://github.com/loveRhythm1990) is this an existing stack? Can you share what your code looks like? Are you configuring your provider with the new `clusterIdentifier` config?
> 
> Edit: I suspect this is due to [#3170](https://github.com/pulumi/pulumi-kubernetes/pull/3170) -- there's something wrong with the config you're trying to apply and we aren't returning the error correctly. As a workaround you can double check your config and fix the error, or you can temporarily remove the `clusterIdentifier` config.

sure, I use `clusterIdentifier`, after i upgrade to version v4.17.1, this problem was fixed, thanks
