### ISSUE TITLE
Panic creating ConfigMap.

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-kubernetes#559]
Please forgive the convoluted example but I'm getting a panic from the following code. I've stripped the functionality down to the bare minimum to cause it. If I create the KeyVault in one update and then create the configmap in the second it all works.

The method to get the kube config from a keyvault works everywhere else, but fails in this case. 

Panic output is at the bottom.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure"
import * as kubernetesInput from "@pulumi/kubernetes/types/input";
import * as kubernetes from "@pulumi/kubernetes";

export const main = async () => {

    const testKeyVault = new azure.keyvault.KeyVault("kv-test", {
        name: "kv-test",
        resourceGroupName: "Infrastructure",
        location: "westeurope",
        sku: { name: "standard" },
        tenantId: azure.config.tenantId || ""
    });

    const getConfigMapSpec = (
        namespace: pulumi.Input<string>,
        key: pulumi.Input<string>,
        contents: pulumi.Input<Object>,
        labels: any = {},
    ): kubernetesInput.core.v1.ConfigMap => pulumi.all([
        key,
        pulumi.output(contents).apply(x => JSON.stringify(x))
    ]).apply(([
        fileName,
        contents
    ]) => {
        let data: { [key: string]: string; } = {};
        data[fileName] = contents;

        return ({
            metadata: {
                namespace: namespace,
                labels: labels,
            },
            data: {
                ...data
            }
        });
    });

    const config = pulumi.all([
        testKeyVault.vaultUri
    ]).apply(([
        keyVaultUri
    ]) =>
        new Object({
            KeyVault: { BaseUrl: keyVaultUri }
        })
    );

    const getProvider = async (
        keyVault: azure.keyvault.GetKeyVaultResult,
        kubeConfigSecretName: string
    ): Promise<kubernetes.Provider> => new Promise(async (resolve, reject) => {
        const kubeConfig = pulumi.output(keyVault.id).apply(x => azure.keyvault.getSecret({
            keyVaultId: x,
            name: kubeConfigSecretName
        }));
        pulumi.output(kubeConfig.value).apply(x => {
            console.log(x);
            resolve(new kubernetes.Provider("Cluster", { kubeconfig: x }))
        });
    });

    const coreKeyVault = await azure.keyvault.getKeyVault({ name: "test", resourceGroupName: "test" });
    const provider = await getProvider(coreKeyVault, "Cluster-KubeConfig");

    new kubernetes.core.v1.ConfigMap(
        "test-configmap",
        getConfigMapSpec("default", "appsettings.json", config),
        { provider: provider }
    );

};
main();

```

```
panic: interface conversion: interface {} is resource.Computed, not map[string]interface {}
    goroutine 159 [running]:
    github.com/pulumi/pulumi-kubernetes/pkg/metadata.SetAnnotation(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/metadata/annotations.go:52
    github.com/pulumi/pulumi-kubernetes/pkg/metadata.SetAnnotationTrue(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/metadata/annotations.go:67
    github.com/pulumi/pulumi-kubernetes/pkg/metadata.AssignNameIfAutonamable(0xc00087f978, 0xc0010e80a7, 0x14)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/metadata/naming.go:35 +0x385
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).Check(0xc0000e9e00, 0x1950600, 0xc0010ea090, 0xc00091af40, 0xc0000e9e00, 0x1523301, 0xc00091af80)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:269 +0x15aa
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x1950600, 0xc0010ea090, 0x1652c80, 0xc00091af40, 0x1671ea0, 0x278d518, 0x1950600, 0xc0010ea090)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1303 +0x8d
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1950600, 0xc0010b5ec0, 0x1652c80, 0xc00091af40, 0xc00093eb40, 0xc00093eb60, 0x0, 0x0, 0x19136e0, 0xc0003f04d0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x367
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x1673660, 0xc0000e9e00, 0x1950600, 0xc0010b5ec0, 0xc0009405f0, 0xc0003f2ea0, 0x1950600, 0xc0010b5ec0, 0xc000a5c780, 0x125)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1305 +0x15f
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000461200, 0x196b800, 0xc000437500, 0xc00050b100, 0xc0003fd3b0, 0x275fa40, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:972 +0x477
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000461200, 0x196b800, 0xc000437500, 0xc00050b100, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:1252 +0xdad
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003a4010, 0xc000461200, 0x196b800, 0xc000437500, 0xc00050b100)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:691 +0xa6
    created by github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:689 +0xa8
```

**Comment by lblackstone** [comment]
I suspect this is caused by computing the ConfigMap metadata rather than creating it directly. The provider currently tries to set an autoname annotation during the preview phase, and I don't think it's handling this case correctly since the metadata isn't yet available.

**Comment by lblackstone** [comment]
Looks like the OP was able to work around by creating the resources in separate updates, so I'm going to punt on this issue for M23

**Comment by joeduffy** [comment]
We can't let panics in the CLI go for another sprint. Assigning @ellismg for load balancing.

**Comment by hausdorff** [comment]
This is caused because `kubeProvider#Check` calls `metadata.AssignNameIfAutonamable` before it checks `!hasComputedValue`. Because the annotations are computed values in this example, we can't very well set them in `Check`. @pgavlin @ellismg we should chat about this on Monday since I've forgotten of the protocol -- but I _believe_ we can fix this by simply setting that value if it's computed?

**Comment by oliverholliday** [comment]
I hit the same panic a few times in different places throughout the last week as it seems to be triggered whenever you use an auto-named kube configmap that contains a value from a newly created resource.

Since it panics during the preview it sent me on a few wild goose chases trying to diagnose which resource is causing the issue - often the output log is something like "Event hub transport closing. <panic stacktrace>".

I was able to work around it in this case with keyvaults but it involved publishing a pre-release npm package with configmap creation commented out then another publish to create that so it was non-trivial. One example where I couldn't work around it was creating an Azure EventHubNamespaceAuthorizationRule and save its keys to a kube configmap - its not possible to create one of those rules and then retrieve its system-generated keys in a separate step.

Thanks a lot.
