### ISSUE TITLE
Panic on updating the stack with azure public ip

### ISSUE THREAD

**Issue by alexeyzimarev** [pulumi/pulumi-kubernetes#564]
I have a running stack in Azure and I made quite a lot of changes in the code _except_ everything that is related to AKS and the public IP for the AKS ingress. Now, when I run the `pulumi up` command, I suddenly get this:

```
     └─ azure:network:PublicIp                    env-test-cu-aksIp                              1 error

Diagnostics:
  pulumi:pulumi:Stack (env-test):
    panic: interface conversion: interface {} is resource.Computed, not string
    goroutine 185 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/resource.PropertyValue.StringValue(...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/resource/properties.go:327
    github.com/pulumi/pulumi-azure.Provider.func1(0xc00099e280, 0xc00009b590, 0x3d3dcfb, 0x8, 0x6c5c320)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/resources.go:967 +0x55e
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformInputs(0xc00099e280, 0xc00009b590, 0xc0005723f0, 0xc0004a4ea0, 0xc0006fda40, 0xc000b45780, 0xc0006fdfb0, 0x1, 0xc0006a4648, 0x107bcdb, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:184 +0xe97
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Check(0xc0001026c0, 0x42f08e0, 0xc0006fdf80, 0xc000b3e140, 0xc0001026c0, 0x3922101, 0xc000b3e180)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:451 +0x679
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x42f08e0, 0xc0006fdf80, 0x3b4e700, 0xc000b3e140, 0x3ba1aa0, 0x6c5ab38, 0x42f08e0, 0xc0006fdf80)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1295 +0x86
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x42f08e0, 0xc0006fde00, 0x3b4e700, 0xc000b3e140, 0xc00099e120, 0xc00099e140, 0x0, 0x0, 0x4286c40, 0xc0002e7580)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2e4
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x3bec540, 0xc0001026c0, 0x42f08e0, 0xc0006fde00, 0xc000720230, 0xc000638020, 0x42f08e0, 0xc0006fde00, 0xc000148820, 0xca)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1297 +0x158
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00051e900, 0x4332a20, 0xc00008f500, 0xc0009d6000, 0xc0006361e0, 0x6c2de40, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:971 +0x470
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00051e900, 0x4332a20, 0xc00008f500, 0xc0009d6000, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1250 +0xd25
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000d4cf0, 0xc00051e900, 0x4332a20, 0xc00008f500, 0xc0009d6000)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:690 +0x9f
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:688 +0xa1

  azure:network:PublicIp (lts-test-cu-aksIp):
    error: transport is closing
```

Again, no changes were made to the ip address code, which looks like this:

```
        const publicIp = new azure.network.PublicIp(schema.getName("aksIp"), {
            name: schema.getName("aksIp"),
            resourceGroupName: k8sCluster.nodeResourceGroup,
            allocationMethod: "Static"
        });
```

Also, no changes were made to the `k8sCluster` provisioning code, but the code to create a service principal for AKS was changed.

**Comment by alexeyzimarev** [comment]
Sorry, wrong repo
