### ISSUE TITLE
Python yaml and helm SDK doesn't work with first-class provider

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#595]
The Python SDK for YAML (`ConfigFile`) and Helm (`Chart`) don't work if a custom provider is specified. For example:

```py3
Chart("nginx-ingress", ChartOpts("stable/nginx-ingress"), opts=ResourceOptions(providers={"kubernetes": k8s_provider}))
ConfigFile(
    "guestbook",
    file_id="https://raw.githubusercontent.com/pulumi/pulumi-kubernetes/master/tests/examples/yaml-guestbook/yaml"
            "/guestbook.yaml",
    opts=ResourceOptions(provider=k8s_provider)
)
```
Running `pulumi up` will start the update and then hang without showing further progress. I tried to debug briefly, and it looks like the following conditionals are the culprits:
https://github.com/pulumi/pulumi-kubernetes/blob/7989847312c7a0b569453e0041b67b5d7506c7af/sdk/python/pulumi_kubernetes/yaml.py#L91-L93
https://github.com/pulumi/pulumi-kubernetes/blob/7989847312c7a0b569453e0041b67b5d7506c7af/sdk/python/pulumi_kubernetes/helm/v2/helm.py#L411-L412

I got the following stack trace:
```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 34, in run_in_stack
        Stack(func)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 93, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 81, in <module>
        opts=ResourceOptions(provider=k8s_provider)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/site-packages/pulumi_kubernetes/yaml.py", line 101, in __init__
        _opts = deepcopy(opts)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/Users/levi/workspace/gke-ingress-python/venv/lib/python3.7/copy.py", line 161, in deepcopy
        y = copier(memo)
    TypeError: 'Output' object is not callable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

It looks like the code isn't properly unwrapping the Output object before attempting to update it.

**Comment by lukehoban** [comment]
I recall running into this when doing Python SDK work and having to fall back on a shallow copy, which isn't necesarrily "right".

We may want to explore implementing a custom `__deepcopy__` on `Output` to fix this generally.

I see this same code pattern in `StackReference` implementation which likely is broken in the same way:

```
opts = deepcopy(opts) if opts is not None else ResourceOptions()
```

**Comment by lukehoban** [comment]
cc also @ellismg and @CyrusNajmabadi

**Comment by lblackstone** [comment]
@CyrusNajmabadi I'm not sure how to proceed here, so bumping over to you to take a look. LMK, if  there's anything I can do to help.
