### ISSUE TITLE
Flaky Istio test seems to be a real issue

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#729]
Specifically the service await logic appears to be incorrect:

```
[                          step1 ] Diagnostics:

[                          step1 ]   pulumi:pulumi:Stack (istio-p-it-travis-job-step1-4ba280ba):

[                          step1 ]     error: Running program '/tmp/p-it-travis-job-step1-4ba280ba-220619603' failed with an unhandled exception:

[                          step1 ]     TypeError: Cannot read property 'loadBalancer' of undefined

[                          step1 ]         at exports.frontendIp.pulumi.all.apply (/tmp/p-it-travis-job-step1-4ba280ba-220619603/index.ts:38:22)

[                          step1 ]         at OutputImpl.<anonymous> (/tmp/p-it-travis-job-step1-4ba280ba-220619603/node_modules/@pulumi/pulumi/output.js:109:47)

[                          step1 ]         at Generator.next (<anonymous>)

[                          step1 ]         at /tmp/p-it-travis-job-step1-4ba280ba-220619603/node_modules/@pulumi/pulumi/output.js:20:71

[                          step1 ]         at new Promise (<anonymous>)

[                          step1 ]         at __awaiter (/tmp/p-it-travis-job-step1-4ba280ba-220619603/node_modules/@pulumi/pulumi/output.js:16:12)

[                          step1 ]         at exports.Output.promise.then (/tmp/p-it-travis-job-step1-4ba280ba-220619603/node_modules/@pulumi/pulumi/output.js:93:70)

[                          step1 ]         at <anonymous>
```

**Comment by hausdorff** [comment]
This turned out to be a result of the initial way we removed `.status` from the inputs. We fixed it in-PR, so this should be good to close out.
