### ISSUE TITLE
YAML deserialization error when booting the Istio Chart in Python

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#764]
The following program—which works with the Node.js SDK—panics the Python SDK.

```python
import pulumi
from pulumi import ResourceOptions
import pulumi_kubernetes
from pulumi_kubernetes.helm.v2 import Chart, LocalChartOpts
from pulumi_kubernetes.apiextensions import CustomResource
from pulumi_kubernetes.core.v1 import Namespace
from pulumi_kubernetes.apps.v1 import Deployment
from pulumi_kubernetes.rbac.v1 import ClusterRoleBinding

ref = pulumi.stack_reference.StackReference('hausdorff/istio/istio-ci-test')
kubeconfig = ref.outputs['kubeconfig']
gcpUsername = ref.outputs['gcpUsername']

provider = pulumi_kubernetes.Provider('test', kubeconfig=kubeconfig)

#
# Istio
#

appName = 'istio'
istioNamespace = f'{appName}-system'
namespace = Namespace(
    istioNamespace,
    metadata={ 'name': istioNamespace },
    opts=ResourceOptions(provider=provider)
)

adminBinding = ClusterRoleBinding(
    'cluster-admin-binding',
    metadata={ 'name': 'cluster-admin-binding' },
    role_ref={
        'apiGroup': 'rbac.authorization.k8s.io',
        'kind': 'ClusterRole',
        'name': 'cluster-admin',
    },
    subjects=[
        { 'apiGroup': 'rbac.authorization.k8s.io', 'kind': 'User', 'name': gcpUsername },
    ],
    opts=ResourceOptions(provider=provider)
)

istio_init = Chart(
    f'{appName}-init',
    LocalChartOpts(
        path='charts/istio-init',
        namespace=istioNamespace,
        values={ 'kiali': { 'enabled': True } },
    ),
    opts=ResourceOptions(provider=provider, depends_on=[namespace, adminBinding])
)

istio = Chart(
    appName,
    LocalChartOpts(
        path="charts/istio",
        namespace=istioNamespace,
        values={ 'kiali': { 'enabled': True } },
    ),
    opts=ResourceOptions(provider=provider, depends_on=[namespace, adminBinding, istio_init])
)
```

```
Previewing update (dev):

     Type                             Name                                     Plan       Info
     pulumi:pulumi:Stack              istio-test-dev                                      3 errors
 +   └─ kubernetes:helm.sh:Chart      istio                                    create
 +      ├─ kubernetes:core:ConfigMap  istio-system/istio-galley-configuration  create
 +      ├─ kubernetes:core:ConfigMap  istio-system/kiali                       create
 +      └─ kubernetes:core:ConfigMap  istio-system/prometheus                  create

Diagnostics:
  pulumi:pulumi:Stack (istio-test-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 41, in run_in_stack
        await RPC_MANAGER.unhandled_exeception()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 414, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 67, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        value = await serialize_property(value.future(), deps, input_transformer)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 147, in serialize_property
        future_return = await asyncio.ensure_future(value)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 149, in run
        value = await self._future
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 311, in gather_futures
        return await asyncio.gather(*value_futures)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 169, in run
        return await transformed.future()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 149, in run
        value = await self._future
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 161, in run
        transformed: Input[U] = func(value)
      File "/Users/alex/go/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin/pulumi_kubernetes/helm/v2/helm.py", line 345, in <lambda>
        lambda yaml_str: _parse_yaml_document(yaml.safe_load_all(yaml_str), opts, config.transformations))
      File "/Users/alex/go/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin/pulumi_kubernetes/yaml.py", line 133, in _parse_yaml_document
        for obj in objects:
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/__init__.py", line 130, in load_all
        yield loader.get_data()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/constructor.py", line 37, in get_data
        return self.construct_document(self.get_node())
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/composer.py", line 27, in get_node
        return self.compose_document()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
        self.current_event = self.state()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
        if self.check_token(KeyToken):
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
        self.fetch_more_tokens()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/yaml/scanner.py", line 260, in fetch_more_tokens
        self.get_mark())
    yaml.scanner.ScannerError: while scanning for the next token
    found character '\t' that cannot start any token
      in "<unicode string>", line 456, column 15:
        apiVersion: v1
                      ^
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by lblackstone** [comment]
We don't use the pyyaml library for this anymore; this logic was moved to an invoke, so it works across languages now.
