### ISSUE TITLE
Depending on Chart.getResource causes an error

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#814]
### Problem description

- I saw an issue in the following Pulumi Program: <URL>

I created a `helm.v2.Chart` and then assigned one of its sub-resources to a variable using `getResource`. Depending on this variable causes an error.

### Errors & Logs

    error: Running program '/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/tests/integration/istio/step1' failed with an unhandled exception:
    TypeError: Cannot read property 'concat' of undefined
        at /opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/runtime/resource.js:359:29
        at Generator.next (<anonymous>)
        at fulfilled (/opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/runtime/resource.js:18:58)

### Reproducing the issue

This works:
```ts
import * as k8s from "@pulumi/kubernetes";

import { k8sProvider } from "./cluster";
import * as config from "./config";

const namespace = new k8s.core.v1.Namespace(
    `istio-system`,
    { metadata: { name: `istio-system` } },
    { provider: k8sProvider }
);

const adminBinding = new k8s.rbac.v1.ClusterRoleBinding(
    "cluster-admin-binding",
    {
        metadata: { name: "cluster-admin-binding" },
        roleRef: {
            apiGroup: "rbac.authorization.k8s.io",
            kind: "ClusterRole",
            name: "cluster-admin"
        },
        subjects: [
            { apiGroup: "rbac.authorization.k8s.io", kind: "User", name: config.gcpUsername }
        ]
    },
    { provider: k8sProvider }
);
export const istio_init = new k8s.helm.v2.Chart(
    `istio-init`,
    {
        path: "charts/istio-init",
        namespace: "istio-system",
        values: { kiali: { enabled: true } }
    },
    { providers: { kubernetes: k8sProvider } }
);

const crd10 = istio_init.getResource("batch/v1/Job", "istio-system", "istio-init-crd-10");
const crd11 = istio_init.getResource("batch/v1/Job", "istio-system", "istio-init-crd-11");
const crd12 = istio_init.getResource("batch/v1/Job", "istio-system", "istio-init-crd-12");

export const istio = new k8s.helm.v2.Chart(
    "istio",
    {
        path: "charts/istio",
        namespace: "istio-system",
        values: { kiali: { enabled: true } }
    },
    { dependsOn: [adminBinding, crd10, crd11, crd12], providers: { kubernetes: k8sProvider } }
);
```

This fails (note the difference on Chart namespaces):
```ts
import * as k8s from "@pulumi/kubernetes";

import { k8sProvider } from "./cluster";
import * as config from "./config";

const namespace = new k8s.core.v1.Namespace(
    `istio-system`,
    { metadata: { name: `istio-system` } },
    { provider: k8sProvider }
);

const adminBinding = new k8s.rbac.v1.ClusterRoleBinding(
    "cluster-admin-binding",
    {
        metadata: { name: "cluster-admin-binding" },
        roleRef: {
            apiGroup: "rbac.authorization.k8s.io",
            kind: "ClusterRole",
            name: "cluster-admin"
        },
        subjects: [
            { apiGroup: "rbac.authorization.k8s.io", kind: "User", name: config.gcpUsername }
        ]
    },
    { provider: k8sProvider }
);
export const istio_init = new k8s.helm.v2.Chart(
    `istio-init`,
    {
        path: "charts/istio-init",
        namespace: namespace.metadata.name,
        values: { kiali: { enabled: true } }
    },
    { providers: { kubernetes: k8sProvider } }
);

const crd10 = istio_init.getResource("batch/v1/Job", "istio-system", "istio-init-crd-10");
const crd11 = istio_init.getResource("batch/v1/Job", "istio-system", "istio-init-crd-11");
const crd12 = istio_init.getResource("batch/v1/Job", "istio-system", "istio-init-crd-12");

export const istio = new k8s.helm.v2.Chart(
    "istio",
    {
        path: "charts/istio",
        namespace: namespace.metadata.name,
        values: { kiali: { enabled: true } }
    },
    { dependsOn: [adminBinding, crd10, crd11, crd12], providers: { kubernetes: k8sProvider } }
);
```

### Suggestions for a fix

My guess is that this has something to do with an unhandled Output during preview.

**Comment by lblackstone** [comment]
I was unable to reproduce this problem, and verified that the original test that uncovered the issue is passing now: https://github.com/pulumi/pulumi-kubernetes/pull/1593

I'm going to close this out since it appears to be fixed, but please comment if anyone runs into it again on a recent version of Pulumi.
