### ISSUE TITLE
On 1.6.x, provider does not autoname resources if EKS cluster is not up yet.

### ISSUE THREAD

**Issue by jeid64** [pulumi/pulumi-kubernetes#906]
### Problem description
Howdy, I have a Pulumi python program that stands up an EKS cluster and then makes a Kubernetes provider that uses the EKS cluster within the same preview. Then the program creates a Kubernetes service account, and uses the name stored in the metadata dictionary to pass that to a Deployment/ClusterRoleBinding. When we switched to 1.6.x we were unable to stand up new stacks due to this error

```
Previewing update (dev):

     Type                                  Name                                         Plan       Info
 +   pulumi:pulumi:Stack                   spinnaker-kubernetes-dev                     create     3 errors
 +   ├─ ekscluster:cluster:cluster         jeid-test-160                                create
 +   │  ├─ aws:ec2:SecurityGroup           jeid-test-160-master-securitygroup           create
 +   │  ├─ aws:iam:Role                    jeid-test-160-master-role                    create
 +   │  ├─ aws:iam:RolePolicyAttachment    jeid-test-160-master-AmazonEKSClusterPolicy  create
 +   │  ├─ aws:iam:RolePolicyAttachment    jeid-test-160-master-AmazonEKSServicePolicy  create
 +   │  └─ aws:eks:Cluster                 jeid-test-160                                create
 +   │     └─ pulumi:providers:kubernetes  jeid-test-160-k8s-provider                   create
 +   └─ kubernetes:core:ServiceAccount     test-service-account2                        create

Diagnostics:
  pulumi:pulumi:Stack (spinnaker-kubernetes-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
        return future.result()
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 72, in run_in_stack
        raise RPC_MANAGER.unhandled_exception.with_traceback(RPC_MANAGER.exception_traceback)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 323, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 88, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 67, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 181, in serialize_property
        obj[transformed_key] = await serialize_property(v, deps, input_transformer)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 181, in serialize_property
        obj[transformed_key] = await serialize_property(v, deps, input_transformer)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 181, in serialize_property
        obj[transformed_key] = await serialize_property(v, deps, input_transformer)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 162, in serialize_property
        value = await serialize_property(value.future(), deps, input_transformer)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_property
        future_return = await asyncio.ensure_future(value)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/output.py", line 108, in get_value
        val = await self._future
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/output.py", line 167, in run
        transformed: Input[U] = func(value)
      File "/Users/jeid/work/pulumi/spinnaker-kubernetes/venv/lib/python3.7/site-packages/pulumi/output.py", line 221, in <lambda>
        return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else v[key], True)
    KeyError: 'name'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Which seems to be happening because our service account is not getting autonamed for some reason here https://github.com/pulumi/pulumi-kubernetes/blob/127ed571e3f357cdf9e02ee86b34d4d6310b7ca6/pkg/provider/provider.go#L778 

Since the service account only gets the ['name'] field in metadata if it gets autonamed, we error, because in preview on 1.6.x the resource is not being autonamed. I believe that its this change thats causing the issue https://github.com/pulumi/pulumi/commit/137fd54f1cdd5ff901ddba0f281039bf3b9a5e01# the git commit explicitly calls out our use case of trying to access the 'name' field, which is broken. 

This only happens if the Provider is referencing an EKS cluster that has _not yet been created_ in preview mode. Our existing stacks that were created on 1.5.1 work fine on 1.6.x because the EKS cluster already exists, and if we downgrade to 1.5.1 we can create new stacks, or if we're on 1.6.x and we do pulumi up --skip-preview it works. 

I've created a git repo here https://github.com/jeid64/pulumi-provider-bug that reproduces the issue. It essentially just makes the EKS controlplane and its dependencies it needs (iam role, security group), then creates the provider, then uses the provider to make a service account, and then use the service account name for a deployment spec. You'll need to set your own subnet-ids and vpc-ids and region here https://github.com/jeid64/pulumi-provider-bug/blob/master/__main__.py#L83

### Affected product version(s)

Pulumi 1.6.1, 1.6.0
running Python 3.7.4 on OS X.
pip list installed shows
```Package           Version
----------------- ---------
Arpeggio          1.9.2
attrs             19.3.0
certifi           2019.9.11
chardet           3.0.4
dill              0.3.1.1
grpcio            1.25.0
idna              2.8
parver            0.2.1
pip               19.3.1
protobuf          3.10.0
pulumi            1.6.1
pulumi-aws        1.8.0
pulumi-kubernetes 1.3.0
PyYAML            5.1.2
requests          2.21.0
semver            2.9.0
setuptools        41.6.0
six               1.13.0
urllib3           1.24.3
wheel             0.33.6```

**Comment by pgavlin** [comment]
Ah, I think I know part of what's going on here--the `metadata` is partially-known, so the `KeyError` is thrown when the lifted property access tries to index into the dictionary, which does not yet include a `name` property. Can you provide some more details regarding the Pulumi program?

**Comment by jeid64** [comment]
@pgavlin I included the entirety of the Pulumi program here  https://github.com/jeid64/pulumi-provider-bug Is there something in particular you would like to know? You should be able to just git clone it, set the vpc-id+subnet-ids+region in code, and then pulumi preview.

**Comment by pgavlin** [comment]
Perfect; thanks! I will clone that and give it a look.

**Comment by pgavlin** [comment]
Okay, so I believe I understand what's happening here.

The autoname is normally set by the k8s provider, but the k8s provider currently cannot do so until the cluster it's targeting exists. Prior to 1.6.x, this was okay: the `metadata` from the service account would have been considered unknown, and the underlying `apply` from the `name` access would not have run. After 1.6.x, this is problematic: the `metadata` is propagated from the inputs and is considered known, so the `name` access occurs and throws a `KeyError`.

Until we have a fix for this, you can use the following workaround:
```diff
diff --git a/__main__.py b/__main__.py
index 0b0964f..2492655 100644
--- a/__main__.py
+++ b/__main__.py
@@ -98,6 +98,7 @@ def eks_stuff():
                                                  "labels": app_labels
                                              }, opts=provresopts)

+    service_account_name = pulumi.Output.all(service_account.id, service_account.metadata).apply(lambda v: v[1]["name"])
     deployment = Deployment(
        "nginx",
        spec={
@@ -107,7 +108,7 @@ def eks_stuff():
                "metadata": { "labels": app_labels
                            },
                "spec": { "containers": [{ "name": "nginx", "image": "nginx" }],
-                         'serviceAccountName': service_account.metadata["name"]} # here's where it breaks
+                         'serviceAccountName': service_account_name}
            }
        })
```

Incorporating the `id` of the service account will ensure that the `apply` does not run until after the service account has been created.

**Comment by pgavlin** [comment]
@lukehoban @CyrusNajmabadi this is going to be a particularly frustrating issue.

The most obvious and correct solution would be to consider the checked inputs for an unconfigured provider as unknown and not propagate them to the state, but that will negatively affect previews. This option would force the issue on implementing support for partial configuration in our providers, which is not necessarily possible in all cases.

Another option may be to consider missing keys in partially-known values as unknowns during preview. I _think_ that this would require some additional changes--I believe that we treat values like `metadata` that do not contain unknowns as fully-known--but it seems like a reasonable compromise.

**Comment by lblackstone** [comment]
Unable to repro on this old issue, so closing it out.
