### ISSUE TITLE
`getResource` not working without explicit default namespace

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#907]
### Problem description

This works
```ts
const grafanaChart = new k8s.helm.v2.Chart(
    "grafana",
    {
        chart: "stable/grafana",
        values: {
            service: { type: "LoadBalancer" },
            testFramework: { enabled: false }
        }
    }
);
export const grafanaHostname = grafanaChart
    .getResourceProperty("v1/Service", "default/grafana", "status")
    .apply(status => status.loadBalancer.ingress[0].hostname);
export const grafanaService = grafanaChart
    .getResource("v1/Service", "default/grafana");
```

This doesn't
```ts
const grafanaChart = new k8s.helm.v2.Chart(
    "grafana",
    {
        chart: "stable/grafana",
        values: {
            service: { type: "LoadBalancer" },
            testFramework: { enabled: false }
        }
    }
);
export const grafanaHostname = grafanaChart
    .getResourceProperty("v1/Service", "grafana", "status")
    .apply(status => status.loadBalancer.ingress[0].hostname);
export const grafanaService = grafanaChart
    .getResource("v1/Service", "grafana");

```
Notice the lack of explicit "default" namespace.

### Errors & Logs

```
    TypeError: Cannot read property 'status' of undefined
        at getResourceImpl.apply.r (/opt/pulumi/node_modules/@pulumi/kubernetes/yaml/yaml.js:85:26)
        at /opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:210:35
        at Generator.next (<anonymous>)
        at /opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:190:12)
        at Promise.all.then (/opt/pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:183:51)
```

#814 may be related.

**Comment by vorotech** [comment]
Hi here,
Small workaround while issue is not fixed

```typescript
const resource = namespace === 'default' 
  ? chart.getResource('v1/Secret', `default/${name}`)
  : chart.getResource('v1/Secret', name, namespace);
```

**Comment by mjeffryes** [comment]
We're not planning to make any more changes to chart v2/v3 at thsi point
