### ISSUE TITLE
Better helm errors

### ISSUE THREAD

**Issue by Panaetius** [pulumi/pulumi-kubernetes#917]
### Problem description

When one of the helm commands (fetch or template) fails in the python version of `pulumi_kubernetes`, the error message is just a generic `subprocess.run` error like `subprocess.CalledProcessError: Command '['helm', 'fetch', '/..../', '--untar', '--version', '1.0', '--destination', '/tmp/tmp5sqt87yp']' returned non-zero exit status 1.`

### Errors & Logs

```
pulumi:pulumi:Stack (dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/zenon/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/home/zenon/.pyenv/versions/3.7.4/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
        return future.result()
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 72, in run_in_stack
        raise RPC_MANAGER.unhandled_exception.with_traceback(RPC_MANAGER.exception_traceback)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 415, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 67, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 162, in serialize_property
        value = await serialize_property(value.future(), deps, input_transformer)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_property
        future_return = await asyncio.ensure_future(value)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/output.py", line 108, in get_value
        val = await self._future
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi/output.py", line 167, in run
        transformed: Input[U] = func(value)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi_kubernetes/helm/v2/helm.py", line 325, in _parse_chart
        _fetch(chart_to_fetch, fetch_opts)
      File "/home/zenon/.pyenv/versions/renku/lib/python3.7/site-packages/pulumi_kubernetes/helm/v2/helm.py", line 392, in _fetch
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, check=True)
      File "/home/zenon/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['helm', 'fetch', '/home/zenon/.../', '--untar', '--version', '1.0', '--destination', '/tmp/tmp5sqt87yp']' returned non-zero exit status 1.
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Suggestions for a fix

https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError already contains the stdout and stderr of the failed command, so it'd be nice to report that to the user along with the exception.

**Comment by EronWright** [comment]
This was fixed long ago when Pulumi switched to using Helm as a library.
