### ISSUE TITLE
ClusterRoleBinding with Incorrect Property

### ISSUE THREAD

**Issue by SamuelMcAravey** [pulumi/pulumi-kubernetes#926]
### Problem description

Trying to create a ClusterRoleBinding via the .Net SDK fails with the error below. This appears to be cause by the output property `Subjects` being types as `Output<Subject[]>` rather than `Output<ImmutableArray<Subject>>`, or something similar. See:
https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/ClusterRoleBinding.cs#L51

### Errors & Logs

When running `pulumi up` this error appears before I get to approve the changes:

```
System.InvalidOperationException: [Output] Pulumi.Kubernetes.Rbac.V1.ClusterRoleBinding.Subjects contains invalid type Pulumi.Kubernetes.Types.Outputs.Rbac.V1.Subject[]. Allowed types are:
        String, Boolean, Int32, Double,
        Nullable<...>, ImmutableArray<...> and ImmutableDictionary<string, ...> or
        a class explicitly marked with the [OutputTypeAttribute].
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.Serialization.OutputCompletionSource.InitializeOutputs(Resource resource)
       at Pulumi.Deployment.Pulumi.IDeploymentInternal.ReadOrRegisterResource(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Resource..ctor(String type, String name, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.CustomResource..ctor(String type, String name, ResourceArgs args, ResourceOptions options)
       at Pulumi.Kubernetes.Rbac.V1.ClusterRoleBinding..ctor(String name, ClusterRoleBindingArgs args, CustomResourceOptions options)
       at Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\src\_rixian\pulumi\rixian-eng\rxn-cluster-configuration\Program.cs:line 128
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Stack.RunInitAsync(Func`1 init)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

### Affected product version(s)

Pulumi CLI: `1.7.1`

| Nuget Package     | Version                        |
|-------------------|--------------------------------|
| Pulumi            | 1.8.0-preview-alpha.1576620705 |
| Pulumi.Azure      | 1.9.0-preview-alpha.1576576694 |
| Pulumi.AzureAD    | 1.4.0-preview                  |
| Pulumi.Kubernetes | 1.5.0-preview-alpha.1576605917 |
| Pulumi.Random     | 1.4.0-preview-alpha.1576145032 |

### Reproducing the issue

The following is the code used. The code came verbaitum from the Crosswalk guide and converting the TypeScript to C#. Specifically this file:
https://github.com/pulumi/kubernetes-guides/blob/master/azure/03-cluster-configuration/index.ts

This is the cleaned up/generalized code that was being run:
[ClusterRoleBindingError.zip](https://github.com/pulumi/pulumi-kubernetes/files/3975954/ClusterRoleBindingError.zip)

### Suggestions for a fix

Not sure of the detail of how the code works since it's generated, but I believe the fix is to update the `ClusterRoleBinding`'s output property `Subjects` to be typed as `Output<ImmutableArray<Types.Outputs.Rbac.V1.Subject>>`.

I potentially spotted the same issue in the following classes (assuming that this really is the cause of the error):

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/ClusterRole.cs#L52

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/ClusterRoleBindingList.cs#L28

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/ClusterRoleList.cs#L28

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/Role.cs#L44

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/RoleBinding.cs#L53

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/RoleBindingList.cs#L28

https://github.com/pulumi/pulumi-kubernetes/blob/18eab106f08286c718e86b6f90882bc4122739b9/sdk/dotnet/Rbac/V1/RoleList.cs#L28

**Comment by SamuelMcAravey** [comment]
FYI, while expanding the code identical errors popped up when using the `Role` and `StorageClass` classes:

**Role**:
```
    System.InvalidOperationException: [Output] Pulumi.Kubernetes.Rbac.V1.Role.Rules contains invalid type Pulumi.Kubernetes.Types.Outputs.Rbac.V1.PolicyRule[]. Allowed types are:
        String, Boolean, Int32, Double,
        Nullable<...>, ImmutableArray<...> and ImmutableDictionary<string, ...> or
        a class explicitly marked with the [OutputTypeAttribute].
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.Serialization.OutputCompletionSource.InitializeOutputs(Resource resource)
       at Pulumi.Deployment.Pulumi.IDeploymentInternal.ReadOrRegisterResource(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Resource..ctor(String type, String name, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.CustomResource..ctor(String type, String name, ResourceArgs args, ResourceOptions options)
       at Pulumi.Kubernetes.Rbac.V1.Role..ctor(String name, RoleArgs args, CustomResourceOptions options)
       at Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\src\_rixian\pulumi\rixian-eng\rxn-cluster-configuration\Program.cs:line 263
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Stack.RunInitAsync(Func`1 init)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**StorageClass**:
```
    System.InvalidOperationException: [Output] Pulumi.Kubernetes.Storage.V1.StorageClass.AllowedTopologies contains invalid type Pulumi.Kubernetes.Types.Outputs.Core.V1.TopologySelectorTerm[]. Allowed types are:
        String, Boolean, Int32, Double,
        Nullable<...>, ImmutableArray<...> and ImmutableDictionary<string, ...> or
        a class explicitly marked with the [OutputTypeAttribute].
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.Serialization.OutputCompletionSource.InitializeOutputs(Resource resource)
       at Pulumi.Deployment.Pulumi.IDeploymentInternal.ReadOrRegisterResource(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Resource..ctor(String type, String name, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.CustomResource..ctor(String type, String name, ResourceArgs args, ResourceOptions options)
       at Pulumi.Kubernetes.Storage.V1.StorageClass..ctor(String name, StorageClassArgs args, CustomResourceOptions options)
       at Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\src\_rixian\pulumi\rixian-eng\rxn-cluster-configuration\Program.cs:line 324
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Stack.RunInitAsync(Func`1 init)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by lukehoban** [comment]
Thanks for the detailed bug report @SamuelMcAravey.
