### ISSUE TITLE
Helm: Chart with absolute url path don't work

### ISSUE THREAD

**Issue by dimapasko** [pulumi/pulumi-kubernetes#949]
### Problem description

When i'm trying to use 

```
new k8s.helm.v2.Chart('vault', {
    chart: "https://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz"
});
```

I'm getting error below.

```
    Error: invalid chart URL format: https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz
    Error: Error: Command failed: helm fetch https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz --untar --destination C:\Users\dpa\AppData\Local\Temp\tmp-4784IGnPuAdgZLTA
    Error: invalid chart URL format: https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\kubernetes\helm\v2\helm.js:120:23
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:220:35
        at Generator.next (<anonymous>)
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:17:12)
        at applyHelperAsync (C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:199:12)
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:179:65
    Error: Error: Command failed: helm fetch https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz --untar --destination C:\Users\dpa\AppData\Local\Temp\tmp-4784IGnPuAdgZLTA
    Error: invalid chart URL format: https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\kubernetes\helm\v2\helm.js:120:23
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:220:35
        at Generator.next (<anonymous>)
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:17:12)
        at applyHelperAsync (C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:199:12)
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:179:65
    Error: Error: Command failed: helm fetch https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz --untar --destination C:\Users\dpa\AppData\Local\Temp\tmp-4784IGnPuAdgZLTA
    Error: invalid chart URL format: https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\kubernetes\helm\v2\helm.js:120:23
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:220:35
        at Generator.next (<anonymous>)
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:17:12)
        at applyHelperAsync (C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:199:12)
        at C:\Scalepoint\Omega\local-kube\node_modules\@pulumi\pulumi\output.js:179:65

    error: Error: Command failed: helm fetch https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz --untar --destination C:\Users\dpa\AppData\Local\Temp\tmp-4784IGnPuAdgZLTA
    Error: invalid chart URL format: https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz
```

Command ```helm fetch https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz --untar --destination C:\Users\dpa\AppData\Local\Temp\tmp-4784IGnPuAdgZLTA```

Fails with: 

```
Error: invalid chart URL format: https\://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz
```

Command ```helm install --name vault https://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz``` - works fine

### Affected product version(s)

OS: Windows 10 latest patch

pulumi version
```v1.8.1```

helm version
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

package.json

```
{
    "name": "local-kube",
    "devDependencies": {
        "@types/node": "^13.1.6",
        "eslint": "6.8.0",
        "@typescript-eslint/eslint-plugin": "2.16.0",
        "@typescript-eslint/parser": "2.16.0",
        "typescript": "^3.7.4"
    },
    "dependencies": {
        "@pulumi/kubernetes": "^1.4.3",
        "@pulumi/kubernetesx": "^0.1.1",
        "@pulumi/pulumi": "^1.8.1",
        "@pulumi/vault": "^1.7.0",
        "@pulumi/query-kubernetes": "^0.1.0",
        "node-cmd": "^3.0.0",
        "nodejs-base64": "^1.0.3",
        "system-installer": "^1.1.0",
        "ntl": "^5.0.0",
        "js-yaml": "^3.13.1"
    }
}
```

### Reproducing the issue

```
new k8s.helm.v2.Chart('vault', {
    chart: "https://github.com/hashicorp/vault-helm/archive/v0.3.0.tar.gz"
});
```

### Suggestions for a fix

It is possble to publish helm template to the private chart & use it

### Related feartures

Functionality about absolute url's in chart was introduced in #284

**Comment by rquitales** [comment]
I believe this is no longer relevant. Helm v3 within our provider now supports URL based charts:

```
const wordpress = new k8s.helm.v3.Chart("wpdev", {
    chart: "https://charts.bitnami.com/bitnami/wordpress-15.2.50.tgz",
});
```

Further, Helm v2 is now deprecated.
