### ISSUE TITLE
Python YAML support failing on a large CRD (cert-manager)

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#984]
### Problem description

- I saw an issue in the following Pulumi Program: 
```py3
from pulumi_kubernetes.yaml import ConfigFile

ConfigFile('test', './cert-manager-minimal.yaml')
```

[python-error.zip](https://github.com/pulumi/pulumi-kubernetes/files/4172819/python-error.zip)

### Errors & Logs

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
        return future.result()
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 38, in run_in_stack
        Stack(func)
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 96, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 3, in <module>
        ConfigFile('test', './cert-manager-minimal.yaml')
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi_kubernetes/yaml.py", line 63, in __init__
        __ret__ = pulumi.runtime.invoke('kubernetes:yaml:decode', {'text': text}).value['result']
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 176, in invoke
        return InvokeResult(_sync_await(asyncio.ensure_future(do_rpc())))
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 92, in _sync_await
        return fut.result()
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 173, in do_rpc
        raise exn
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 157, in do_invoke
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/levi/workspace/python-error/venv/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 155, in do_invoke
        raise Exception(details)
    Exception: Exception deserializing response!
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by lblackstone** [comment]
This seems to be the same issue reported here: https://github.com/bblfsh/python-client/issues/89#issuecomment-445809692

I updated `pulumi/runtime/invoke.py` with the following import, and that seemed to fix it:

```py
from google.protobuf.pyext._message import SetAllowOversizeProtos
SetAllowOversizeProtos(True)
```

**Comment by squarebracket** [comment]
FWIW I am also seeing YAML failures in 1.5.1 from the node.js sdk.

**Comment by lblackstone** [comment]
@squarebracket Can you open a new issue with details? Is this the same as #978?

**Comment by squarebracket** [comment]
I don't think so; it was complaining that it couldn't get `status` of `undefined`. I had to lock to v1.4.3, and typescript complains every time I change a version when I'm using a library, so I have to do a bunch of things every time I change a version. So I'll open an issue as soon as I can, but I can't open one right now.

**Comment by xadcoh** [comment]
Facing this issue with pulumi 2.1.0
